// Databáze příkladů pro procvičování chemického názvosloví solí

export const GROUPS = {
  BEZKYSLICATE: 'bezkyslíkaté',
  KYSLICATE: 'kyslíkaté',
  HYDRATY: 'hydráty',
  PODVOJNE: 'podvojné',
  ZASADITE: 'zásadité',
};

export const examples = [

  // ═══════════════════════════════════════════════════════════════════════════
  // SOLI BEZKYSLÍKATÝCH KYSELIN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 1,
    formula: 'NaCl',
    name: 'chlorid sodný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'NaCl je sůl kyseliny chlorovodíkové. Kation Na⁺ → sodný, anion Cl⁻ → chlorid.',
    tip: 'NaCl = kuchyňská sůl. Chlorid + sodný.',
    acceptedNames: ['chlorid sodný'],
    acceptedFormulas: ['NaCl'],
  },
  {
    id: 2,
    formula: 'KBr',
    name: 'bromid draselný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'KBr je sůl kyseliny bromovodíkové. K⁺ → draselný, Br⁻ → bromid.',
    tip: 'Br⁻ = bromid (jako bróm). K⁺ = draselný.',
    acceptedNames: ['bromid draselný'],
    acceptedFormulas: ['KBr'],
  },
  {
    id: 3,
    formula: 'CaF₂',
    name: 'fluorid vápenatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Ca²⁺ = vápenatý, F⁻ = fluorid. Dva fluoridy na jeden kation: CaF₂.',
    tip: 'F⁻ = fluorid. Ca²⁺ = vápenatý (vždy +II).',
    acceptedNames: ['fluorid vápenatý'],
    acceptedFormulas: ['CaF2', 'CaF₂'],
  },
  {
    id: 4,
    formula: 'FeS',
    name: 'sulfid železnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Fe²⁺ = železnatý (ox. č. II), S²⁻ = sulfid. Náboje 2+ a 2− → poměr 1:1.',
    tip: 'FeS: stejný počet atomů → Fe má ox. č. = náboj S²⁻ = +II → železnatý.',
    acceptedNames: ['sulfid železnatý'],
    acceptedFormulas: ['FeS'],
  },
  {
    id: 5,
    formula: 'Fe₂S₃',
    name: 'sulfid železitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Fe³⁺ = železitý (ox. č. III), S²⁻ = sulfid. 2×(+3) + 3×(−2) = 0.',
    tip: 'Fe₂S₃: více síry než železa → Fe musí mít vyšší ox. číslo → +III → železitý.',
    acceptedNames: ['sulfid železitý'],
    acceptedFormulas: ['Fe2S3', 'Fe₂S₃'],
  },
  {
    id: 6,
    formula: 'CuI',
    name: 'jodid měďný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Cu⁺ = měďný (ox. č. I), I⁻ = jodid.',
    tip: 'Cu⁺ = měďný, Cu²⁺ = měďnatý. CuI: 1:1 → Cu má ox. č. +I.',
    acceptedNames: ['jodid měďný'],
    acceptedFormulas: ['CuI'],
  },
  {
    id: 7,
    formula: 'AlCl₃',
    name: 'chlorid hlinitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý, Cl⁻ = chlorid. Tři Cl⁻ na jeden Al³⁺.',
    tip: 'Hliník = vždy +III → hlinitý.',
    acceptedNames: ['chlorid hlinitý'],
    acceptedFormulas: ['AlCl3', 'AlCl₃'],
  },
  {
    id: 8,
    formula: 'PbS₂',
    name: 'sulfid olovičitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 3,
    explanation: 'Pb⁴⁺ = olovičitý (ox. č. IV), S²⁻ = sulfid. 1×(+4) + 2×(−2) = 0.',
    tip: 'Pb²⁺ = olovnatý, Pb⁴⁺ = olovičitý. PbS₂: dvě síry → ox. č. +IV.',
    acceptedNames: ['sulfid olovičitý'],
    acceptedFormulas: ['PbS2', 'PbS₂'],
  },
  {
    id: 9,
    formula: 'MgBr₂',
    name: 'bromid hořečnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, Br⁻ = bromid. Dva bromidy na jeden kation.',
    tip: 'Hořčík = vždy +II → hořečnatý.',
    acceptedNames: ['bromid hořečnatý'],
    acceptedFormulas: ['MgBr2', 'MgBr₂'],
  },
  {
    id: 10,
    formula: 'ZnCl₂',
    name: 'chlorid zinečnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Zn²⁺ = zinečnatý, Cl⁻ = chlorid. Dva chloridy.',
    tip: 'Zinek = vždy +II → zinečnatý.',
    acceptedNames: ['chlorid zinečnatý'],
    acceptedFormulas: ['ZnCl2', 'ZnCl₂'],
  },
  {
    id: 11,
    formula: 'AgCl',
    name: 'chlorid stříbrný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Ag⁺ = stříbrný (ox. č. I), Cl⁻ = chlorid.',
    tip: 'Stříbro = vždy +I → stříbrný. AgCl je nerozpustná bílá sraženina.',
    acceptedNames: ['chlorid stříbrný'],
    acceptedFormulas: ['AgCl'],
  },
  {
    id: 12,
    formula: 'HgCl₂',
    name: 'chlorid rtuťnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Hg²⁺ = rtuťnatý (ox. č. II), Cl⁻ = chlorid. Dva Cl na jeden Hg.',
    tip: 'Hg²⁺ = rtuťnatý, Hg₂²⁺ = rtuťný (tricky!). HgCl₂ = sublimát.',
    acceptedNames: ['chlorid rtuťnatý'],
    acceptedFormulas: ['HgCl2', 'HgCl₂'],
  },
  {
    id: 13,
    formula: 'CrCl₃',
    name: 'chlorid chromitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Cr³⁺ = chromitý (ox. č. III), Cl⁻ = chlorid. Tři Cl⁻.',
    tip: 'Chrom: Cr²⁺ = chromatý, Cr³⁺ = chromitý, Cr⁶⁺ = chromový.',
    acceptedNames: ['chlorid chromitý'],
    acceptedFormulas: ['CrCl3', 'CrCl₃'],
  },
  {
    id: 14,
    formula: 'MnCl₂',
    name: 'chlorid manganatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Mn²⁺ = manganatý (ox. č. II), Cl⁻ = chlorid.',
    tip: 'Mangan (Mn): nejčastější ox. č. +II → manganatý.',
    acceptedNames: ['chlorid manganatý'],
    acceptedFormulas: ['MnCl2', 'MnCl₂'],
  },
  {
    id: 15,
    formula: 'NiS',
    name: 'sulfid nikelnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Ni²⁺ = nikelnatý, S²⁻ = sulfid. Poměr 1:1.',
    tip: 'Nikl: nejčastější +II → nikelnatý.',
    acceptedNames: ['sulfid nikelnatý'],
    acceptedFormulas: ['NiS'],
  },
  {
    id: 16,
    formula: 'CoS',
    name: 'sulfid kobaltnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Co²⁺ = kobaltnatý, S²⁻ = sulfid. Poměr 1:1.',
    tip: 'Kobalt: +II = kobaltnatý, +III = kobaltitý.',
    acceptedNames: ['sulfid kobaltnatý'],
    acceptedFormulas: ['CoS'],
  },
  {
    id: 17,
    formula: 'SnCl₂',
    name: 'chlorid cínatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Sn²⁺ = cínatý (ox. č. II), Cl⁻ = chlorid. Dva Cl.',
    tip: 'Cín: Sn²⁺ = cínatý, Sn⁴⁺ = cíničitý.',
    acceptedNames: ['chlorid cínatý'],
    acceptedFormulas: ['SnCl2', 'SnCl₂'],
  },
  {
    id: 18,
    formula: 'SnCl₄',
    name: 'chlorid cíničitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 3,
    explanation: 'Sn⁴⁺ = cíničitý (ox. č. IV), Cl⁻ = chlorid. Čtyři Cl.',
    tip: 'Čtyři Cl → ox. č. Sn = +IV → cíničitý.',
    acceptedNames: ['chlorid cíničitý'],
    acceptedFormulas: ['SnCl4', 'SnCl₄'],
  },
  {
    id: 19,
    formula: 'BiCl₃',
    name: 'chlorid bismutitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 3,
    explanation: 'Bi³⁺ = bismutitý (ox. č. III), Cl⁻ = chlorid. Tři Cl.',
    tip: 'Bismut: vždy +III → bismutitý.',
    acceptedNames: ['chlorid bismutitý'],
    acceptedFormulas: ['BiCl3', 'BiCl₃'],
  },
  {
    id: 20,
    formula: 'CaI₂',
    name: 'jodid vápenatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Ca²⁺ = vápenatý, I⁻ = jodid. Dva jodidy.',
    tip: 'I⁻ = jodid. Vápník = vždy +II.',
    acceptedNames: ['jodid vápenatý'],
    acceptedFormulas: ['CaI2', 'CaI₂'],
  },
  {
    id: 21,
    formula: 'NaI',
    name: 'jodid sodný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Na⁺ = sodný, I⁻ = jodid.',
    tip: 'NaI se přidává do jodizované soli (prevence nedostatku jódu).',
    acceptedNames: ['jodid sodný'],
    acceptedFormulas: ['NaI'],
  },
  {
    id: 22,
    formula: 'PbCl₂',
    name: 'chlorid olovnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Pb²⁺ = olovnatý (ox. č. II), Cl⁻ = chlorid. Dva Cl.',
    tip: 'Pb²⁺ = olovnatý (nižší ox. č.), Pb⁴⁺ = olovičitý.',
    acceptedNames: ['chlorid olovnatý'],
    acceptedFormulas: ['PbCl2', 'PbCl₂'],
  },
  {
    id: 23,
    formula: 'CuBr₂',
    name: 'bromid měďnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Cu²⁺ = měďnatý (ox. č. II), Br⁻ = bromid. Dva bromidy.',
    tip: 'CuBr₂: dva Br → Cu má ox. č. +II → měďnatý.',
    acceptedNames: ['bromid měďnatý'],
    acceptedFormulas: ['CuBr2', 'CuBr₂'],
  },
  {
    id: 24,
    formula: 'BaF₂',
    name: 'fluorid barnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Ba²⁺ = barnatý, F⁻ = fluorid. Dva fluoridy.',
    tip: 'Baryum = vždy +II → barnatý.',
    acceptedNames: ['fluorid barnatý'],
    acceptedFormulas: ['BaF2', 'BaF₂'],
  },
  {
    id: 25,
    formula: 'K₂S',
    name: 'sulfid draselný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'K⁺ = draselný, S²⁻ = sulfid. Dva kationty draslíku.',
    tip: 'Draslík = +I → dva K⁺ na jeden S²⁻.',
    acceptedNames: ['sulfid draselný'],
    acceptedFormulas: ['K2S', 'K₂S'],
  },
  {
    id: 26,
    formula: 'Na₂S',
    name: 'sulfid sodný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Na⁺ = sodný, S²⁻ = sulfid. Dva sodíky.',
    tip: 'Sodík = +I → dva Na⁺ na jeden S²⁻.',
    acceptedNames: ['sulfid sodný'],
    acceptedFormulas: ['Na2S', 'Na₂S'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SOLI KYSLÍKATÝCH KYSELIN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 27,
    formula: 'Na₂SO₄',
    name: 'síran sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'SO₄²⁻ = síran (H₂SO₄), Na⁺ = sodný. Dva sodíky.',
    tip: 'SO₄²⁻ = síran. Nezaměňovat se siřičitanem (SO₃²⁻).',
    acceptedNames: ['síran sodný'],
    acceptedFormulas: ['Na2SO4', 'Na₂SO₄'],
  },
  {
    id: 28,
    formula: 'CaCO₃',
    name: 'uhličitan vápenatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'CO₃²⁻ = uhličitan (H₂CO₃), Ca²⁺ = vápenatý.',
    tip: 'CaCO₃ = vápenec, mramor, křída. CO₃²⁻ = uhličitan.',
    acceptedNames: ['uhličitan vápenatý'],
    acceptedFormulas: ['CaCO3', 'CaCO₃'],
  },
  {
    id: 29,
    formula: 'KNO₃',
    name: 'dusičnan draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'NO₃⁻ = dusičnan (HNO₃), K⁺ = draselný.',
    tip: 'KNO₃ = ledek draselný. NO₃⁻ = dusičnan.',
    acceptedNames: ['dusičnan draselný'],
    acceptedFormulas: ['KNO3', 'KNO₃'],
  },
  {
    id: 30,
    formula: 'Na₃PO₄',
    name: 'fosforečnan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'PO₄³⁻ = fosforečnan (H₃PO₄), Na⁺ = sodný. Tři sodíky.',
    tip: 'PO₄³⁻ = fosforečnan. H₃PO₄ má tři kyselé vodíky → tři Na⁺.',
    acceptedNames: ['fosforečnan sodný'],
    acceptedFormulas: ['Na3PO4', 'Na₃PO₄'],
  },
  {
    id: 31,
    formula: 'Fe₂(SO₄)₃',
    name: 'síran železitý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Fe³⁺ = železitý, SO₄²⁻ = síran. 2×(+3) + 3×(−2) = 0.',
    tip: 'Závorky u SO₄ jsou nutné, pokud je jich více než jedna.',
    acceptedNames: ['síran železitý'],
    acceptedFormulas: ['Fe2(SO4)3', 'Fe₂(SO₄)₃'],
  },
  {
    id: 32,
    formula: 'BaSO₄',
    name: 'síran barnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Ba²⁺ = barnatý, SO₄²⁻ = síran. Poměr 1:1.',
    tip: 'BaSO₄ je nerozpustný → používá se jako kontrastní látka v RTG.',
    acceptedNames: ['síran barnatý'],
    acceptedFormulas: ['BaSO4', 'BaSO₄'],
  },
  {
    id: 33,
    formula: 'Cu(NO₃)₂',
    name: 'dusičnan měďnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Cu²⁺ = měďnatý, NO₃⁻ = dusičnan. Dva dusičnany.',
    tip: 'Závorky: (NO₃)₂ protože více než jeden dusičnan.',
    acceptedNames: ['dusičnan měďnatý'],
    acceptedFormulas: ['Cu(NO3)2', 'Cu(NO₃)₂'],
  },
  {
    id: 34,
    formula: 'Al₂(SO₄)₃',
    name: 'síran hlinitý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý, SO₄²⁻ = síran. 2×(+3) + 3×(−2) = 0.',
    tip: 'Základ kamence. Al je vždy +III → hlinitý.',
    acceptedNames: ['síran hlinitý'],
    acceptedFormulas: ['Al2(SO4)3', 'Al₂(SO₄)₃'],
  },
  {
    id: 35,
    formula: 'NaHCO₃',
    name: 'hydrogenuhličitan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'HCO₃⁻ = hydrogenuhličitan (H₂CO₃ odštěpila jen jeden H⁺).',
    tip: 'NaHCO₃ = jedlá soda. Hydrogen- = zůstal jeden H.',
    acceptedNames: ['hydrogenuhličitan sodný'],
    acceptedFormulas: ['NaHCO3', 'NaHCO₃'],
  },
  {
    id: 36,
    formula: 'K₂Cr₂O₇',
    name: 'dichroman draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'Cr₂O₇²⁻ = dichroman (dva atomy Cr). K⁺ = draselný. Dva draslíky.',
    tip: 'K₂Cr₂O₇ je oranžový oxidant. di- = dva atomy chromu.',
    acceptedNames: ['dichroman draselný'],
    acceptedFormulas: ['K2Cr2O7', 'K₂Cr₂O₇'],
  },
  {
    id: 37,
    formula: 'KMnO₄',
    name: 'manganistan draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'MnO₄⁻ = manganistan (Mn má ox. č. +VII), K⁺ = draselný.',
    tip: 'KMnO₄ = fialový oxidant. MnO₄⁻ = manganistan (HMnO₄).',
    acceptedNames: ['manganistan draselný'],
    acceptedFormulas: ['KMnO4', 'KMnO₄'],
  },
  {
    id: 38,
    formula: 'K₂MnO₄',
    name: 'mangannan draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'MnO₄²⁻ = mangannan (Mn má ox. č. +VI), K⁺ = draselný. Dva draslíky.',
    tip: 'Rozlišuj: MnO₄⁻ = manganistan (Mn +VII), MnO₄²⁻ = mangannan (Mn +VI).',
    acceptedNames: ['mangannan draselný'],
    acceptedFormulas: ['K2MnO4', 'K₂MnO₄'],
  },
  {
    id: 39,
    formula: 'NaNO₂',
    name: 'dusitan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'NO₂⁻ = dusitan (HNO₂ = kyselina dusitá), Na⁺ = sodný.',
    tip: 'Dusitan (NO₂⁻) vs dusičnan (NO₃⁻): dusitan má méně kyslíku.',
    acceptedNames: ['dusitan sodný'],
    acceptedFormulas: ['NaNO2', 'NaNO₂'],
  },
  {
    id: 40,
    formula: 'Ca(NO₃)₂',
    name: 'dusičnan vápenatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Ca²⁺ = vápenatý, NO₃⁻ = dusičnan. Dva dusičnany.',
    tip: 'Vápník = +II → dva NO₃⁻.',
    acceptedNames: ['dusičnan vápenatý'],
    acceptedFormulas: ['Ca(NO3)2', 'Ca(NO₃)₂'],
  },
  {
    id: 41,
    formula: 'K₂SO₄',
    name: 'síran draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'SO₄²⁻ = síran, K⁺ = draselný. Dva draslíky.',
    tip: 'Draslík = +I → dva K⁺ na SO₄²⁻.',
    acceptedNames: ['síran draselný'],
    acceptedFormulas: ['K2SO4', 'K₂SO₄'],
  },
  {
    id: 42,
    formula: 'MgSO₄',
    name: 'síran hořečnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Mg²⁺ = hořečnatý, SO₄²⁻ = síran. Poměr 1:1.',
    tip: 'MgSO₄ bezvodý = hořká sůl. Hořčík = +II.',
    acceptedNames: ['síran hořečnatý'],
    acceptedFormulas: ['MgSO4', 'MgSO₄'],
  },
  {
    id: 43,
    formula: 'ZnSO₄',
    name: 'síran zinečnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Zn²⁺ = zinečnatý, SO₄²⁻ = síran.',
    tip: 'Zinek = +II → zinečnatý. ZnSO₄ = bílý vitriol.',
    acceptedNames: ['síran zinečnatý'],
    acceptedFormulas: ['ZnSO4', 'ZnSO₄'],
  },
  {
    id: 44,
    formula: 'Ca₃(PO₄)₂',
    name: 'fosforečnan vápenatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'PO₄³⁻ = fosforečnan, Ca²⁺ = vápenatý. 3×(+2) + 2×(−3) = 0.',
    tip: 'Hlavní složka kostí a zubů. Tři Ca²⁺ a dva PO₄³⁻.',
    acceptedNames: ['fosforečnan vápenatý'],
    acceptedFormulas: ['Ca3(PO4)2', 'Ca₃(PO₄)₂'],
  },
  {
    id: 45,
    formula: 'AgNO₃',
    name: 'dusičnan stříbrný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Ag⁺ = stříbrný, NO₃⁻ = dusičnan. Poměr 1:1.',
    tip: 'AgNO₃ = lapis, používá se v analytické chemii i fotografii.',
    acceptedNames: ['dusičnan stříbrný'],
    acceptedFormulas: ['AgNO3', 'AgNO₃'],
  },
  {
    id: 46,
    formula: 'Pb(NO₃)₂',
    name: 'dusičnan olovnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Pb²⁺ = olovnatý, NO₃⁻ = dusičnan. Dva dusičnany.',
    tip: 'Pb²⁺ = olovnatý. Pozor: jeden z mála dobře rozpustných solí olova.',
    acceptedNames: ['dusičnan olovnatý'],
    acceptedFormulas: ['Pb(NO3)2', 'Pb(NO₃)₂'],
  },
  {
    id: 47,
    formula: 'K₂CrO₄',
    name: 'chroman draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'CrO₄²⁻ = chroman (Cr +VI), K⁺ = draselný. Dva draslíky.',
    tip: 'Chroman (CrO₄²⁻) = žlutý, dichroman (Cr₂O₇²⁻) = oranžový.',
    acceptedNames: ['chroman draselný'],
    acceptedFormulas: ['K2CrO4', 'K₂CrO₄'],
  },
  {
    id: 48,
    formula: 'FeSO₄',
    name: 'síran železnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Fe²⁺ = železnatý, SO₄²⁻ = síran. Poměr 1:1.',
    tip: 'FeSO₄ = zelený vitriol. Fe²⁺ = železnatý (+II).',
    acceptedNames: ['síran železnatý'],
    acceptedFormulas: ['FeSO4', 'FeSO₄'],
  },
  {
    id: 49,
    formula: 'Na₂SO₃',
    name: 'siřičitan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'SO₃²⁻ = siřičitan (H₂SO₃ = kyselina siřičitá), Na⁺ = sodný.',
    tip: 'Siřičitan SO₃²⁻ vs síran SO₄²⁻: siřičitan má méně kyslíku.',
    acceptedNames: ['siřičitan sodný'],
    acceptedFormulas: ['Na2SO3', 'Na₂SO₃'],
  },
  {
    id: 50,
    formula: 'CaSO₃',
    name: 'siřičitan vápenatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Ca²⁺ = vápenatý, SO₃²⁻ = siřičitan.',
    tip: 'SO₃²⁻ = siřičitan (kyselina siřičitá H₂SO₃).',
    acceptedNames: ['siřičitan vápenatý'],
    acceptedFormulas: ['CaSO3', 'CaSO₃'],
  },
  {
    id: 51,
    formula: 'Na₂SiO₃',
    name: 'křemičitan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'SiO₃²⁻ = křemičitan (H₂SiO₃), Na⁺ = sodný. Dva sodíky.',
    tip: 'Na₂SiO₃ = vodní sklo. SiO₃²⁻ = křemičitan.',
    acceptedNames: ['křemičitan sodný'],
    acceptedFormulas: ['Na2SiO3', 'Na₂SiO₃'],
  },
  {
    id: 52,
    formula: 'NaH₂PO₄',
    name: 'dihydrogenfosforečnan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'H₂PO₄⁻ = dihydrogenfosforečnan (H₃PO₄ odštěpila jen jeden H⁺, dva zbývají). Jeden Na⁺.',
    tip: 'dihydrogen- = zůstaly dva kyselé vodíky. Třikrok: H₃PO₄ → H₂PO₄⁻ → HPO₄²⁻ → PO₄³⁻.',
    acceptedNames: ['dihydrogenfosforečnan sodný'],
    acceptedFormulas: ['NaH2PO4', 'NaH₂PO₄'],
  },
  {
    id: 53,
    formula: 'Na₂HPO₄',
    name: 'hydrogenfosforečnan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'HPO₄²⁻ = hydrogenfosforečnan (H₃PO₄ odštěpila dva H⁺, jeden zbývá). Dva Na⁺.',
    tip: 'hydrogen- = zbyl jeden kyselý vodík. Přípona je jiná než dihydrogen-.',
    acceptedNames: ['hydrogenfosforečnan sodný'],
    acceptedFormulas: ['Na2HPO4', 'Na₂HPO₄'],
  },
  {
    id: 54,
    formula: 'KHSO₄',
    name: 'hydrogensíran draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'HSO₄⁻ = hydrogensíran (H₂SO₄ odštěpila jen jeden H⁺), K⁺ = draselný.',
    tip: 'KHSO₄ = kyselý síran draselný. hydrogen- = zbyl jeden H.',
    acceptedNames: ['hydrogensíran draselný'],
    acceptedFormulas: ['KHSO4', 'KHSO₄'],
  },
  {
    id: 55,
    formula: 'Mg(NO₃)₂',
    name: 'dusičnan hořečnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, NO₃⁻ = dusičnan. Dva dusičnany.',
    tip: 'Hořčík = +II → dva NO₃⁻.',
    acceptedNames: ['dusičnan hořečnatý'],
    acceptedFormulas: ['Mg(NO3)2', 'Mg(NO₃)₂'],
  },
  {
    id: 56,
    formula: 'FePO₄',
    name: 'fosforečnan železitý',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'Fe³⁺ = železitý, PO₄³⁻ = fosforečnan. Náboje +3 a −3 → poměr 1:1.',
    tip: 'Fe³⁺ a PO₄³⁻ mají stejný náboj → FePO₄ (1:1, bez závorek).',
    acceptedNames: ['fosforečnan železitý'],
    acceptedFormulas: ['FePO4', 'FePO₄'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HYDRÁTY SOLÍ
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 57,
    formula: 'CuSO₄ · 5H₂O',
    name: 'síran měďnatý pentahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 1,
    explanation: 'Pět molekul vody → pentahydrát. CuSO₄ = síran měďnatý. Modrý vitriol.',
    tip: 'penta = 5. CuSO₄ bezvodý je bílý, s vodou modrý.',
    acceptedNames: ['síran měďnatý pentahydrát', 'pentahydrát síranu měďnatého'],
    acceptedFormulas: ['CuSO4·5H2O', 'CuSO4 · 5H2O', 'CuSO₄·5H₂O', 'CuSO₄ · 5H₂O'],
  },
  {
    id: 58,
    formula: 'Na₂SO₄ · 10H₂O',
    name: 'síran sodný dekahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 1,
    explanation: 'Deset molekul vody → dekahydrát. Na₂SO₄ = síran sodný. Glauberova sůl.',
    tip: 'deka = 10. Glauberova sůl = Na₂SO₄·10H₂O.',
    acceptedNames: ['síran sodný dekahydrát', 'dekahydrát síranu sodného'],
    acceptedFormulas: ['Na2SO4·10H2O', 'Na2SO4 · 10H2O', 'Na₂SO₄·10H₂O', 'Na₂SO₄ · 10H₂O'],
  },
  {
    id: 59,
    formula: 'MgSO₄ · 7H₂O',
    name: 'síran hořečnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Sedm molekul vody → heptahydrát. MgSO₄ = síran hořečnatý. Epsomská sůl.',
    tip: 'hepta = 7. Epsomská sůl = MgSO₄·7H₂O.',
    acceptedNames: ['síran hořečnatý heptahydrát', 'heptahydrát síranu hořečnatého'],
    acceptedFormulas: ['MgSO4·7H2O', 'MgSO4 · 7H2O', 'MgSO₄·7H₂O', 'MgSO₄ · 7H₂O'],
  },
  {
    id: 60,
    formula: 'CaCl₂ · 6H₂O',
    name: 'chlorid vápenatý hexahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Šest molekul vody → hexahydrát. CaCl₂ = chlorid vápenatý.',
    tip: 'hexa = 6. Bezvodý CaCl₂ se používá jako vysoušedlo.',
    acceptedNames: ['chlorid vápenatý hexahydrát', 'hexahydrát chloridu vápenatého'],
    acceptedFormulas: ['CaCl2·6H2O', 'CaCl2 · 6H2O', 'CaCl₂·6H₂O', 'CaCl₂ · 6H₂O'],
  },
  {
    id: 61,
    formula: 'FeSO₄ · 7H₂O',
    name: 'síran železnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Fe²⁺ = železnatý, SO₄²⁻ = síran, 7H₂O = heptahydrát. Zelený vitriol.',
    tip: 'hepta = 7. Zelený vitriol = FeSO₄·7H₂O.',
    acceptedNames: ['síran železnatý heptahydrát', 'heptahydrát síranu železnatého'],
    acceptedFormulas: ['FeSO4·7H2O', 'FeSO4 · 7H2O', 'FeSO₄·7H₂O', 'FeSO₄ · 7H₂O'],
  },
  {
    id: 62,
    formula: 'Na₂CO₃ · 10H₂O',
    name: 'uhličitan sodný dekahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Na₂CO₃ = uhličitan sodný, 10H₂O = dekahydrát. Krystalická soda.',
    tip: 'deka = 10. Krystalická soda = Na₂CO₃·10H₂O.',
    acceptedNames: ['uhličitan sodný dekahydrát', 'dekahydrát uhličitanu sodného'],
    acceptedFormulas: ['Na2CO3·10H2O', 'Na2CO3 · 10H2O', 'Na₂CO₃·10H₂O', 'Na₂CO₃ · 10H₂O'],
  },
  {
    id: 63,
    formula: 'AlCl₃ · 6H₂O',
    name: 'chlorid hlinitý hexahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 3,
    explanation: 'AlCl₃ = chlorid hlinitý, 6H₂O = hexahydrát.',
    tip: 'hexa = 6. Al = +III → hlinitý.',
    acceptedNames: ['chlorid hlinitý hexahydrát', 'hexahydrát chloridu hlinitého'],
    acceptedFormulas: ['AlCl3·6H2O', 'AlCl3 · 6H2O', 'AlCl₃·6H₂O', 'AlCl₃ · 6H₂O'],
  },
  {
    id: 64,
    formula: 'ZnSO₄ · 7H₂O',
    name: 'síran zinečnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'ZnSO₄ = síran zinečnatý, 7H₂O = heptahydrát. Bílý vitriol.',
    tip: 'hepta = 7. Bílý vitriol = ZnSO₄·7H₂O.',
    acceptedNames: ['síran zinečnatý heptahydrát', 'heptahydrát síranu zinečnatého'],
    acceptedFormulas: ['ZnSO4·7H2O', 'ZnSO4 · 7H2O', 'ZnSO₄·7H₂O', 'ZnSO₄ · 7H₂O'],
  },
  {
    id: 65,
    formula: 'NiSO₄ · 7H₂O',
    name: 'síran nikelnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 3,
    explanation: 'Ni²⁺ = nikelnatý, SO₄²⁻ = síran, 7H₂O = heptahydrát.',
    tip: 'hepta = 7. NiSO₄·7H₂O je smaragdově zelený.',
    acceptedNames: ['síran nikelnatý heptahydrát', 'heptahydrát síranu nikelnatého'],
    acceptedFormulas: ['NiSO4·7H2O', 'NiSO4 · 7H2O', 'NiSO₄·7H₂O', 'NiSO₄ · 7H₂O'],
  },
  {
    id: 66,
    formula: 'CuCl₂ · 2H₂O',
    name: 'chlorid měďnatý dihydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'CuCl₂ = chlorid měďnatý, 2H₂O = dihydrát.',
    tip: 'di = 2. CuCl₂·2H₂O je modrý, bezvodý CuCl₂ je hnědý.',
    acceptedNames: ['chlorid měďnatý dihydrát', 'dihydrát chloridu měďnatého'],
    acceptedFormulas: ['CuCl2·2H2O', 'CuCl2 · 2H2O', 'CuCl₂·2H₂O', 'CuCl₂ · 2H₂O'],
  },
  {
    id: 67,
    formula: 'BaCl₂ · 2H₂O',
    name: 'chlorid barnatý dihydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'BaCl₂ = chlorid barnatý, 2H₂O = dihydrát.',
    tip: 'di = 2. Baryum = +II → barnatý.',
    acceptedNames: ['chlorid barnatý dihydrát', 'dihydrát chloridu barnatého'],
    acceptedFormulas: ['BaCl2·2H2O', 'BaCl2 · 2H2O', 'BaCl₂·2H₂O', 'BaCl₂ · 2H₂O'],
  },
  {
    id: 68,
    formula: 'CoSO₄ · 7H₂O',
    name: 'síran kobaltnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 3,
    explanation: 'Co²⁺ = kobaltnatý, SO₄²⁻ = síran, 7H₂O = heptahydrát.',
    tip: 'hepta = 7. CoSO₄·7H₂O je červený.',
    acceptedNames: ['síran kobaltnatý heptahydrát', 'heptahydrát síranu kobaltnatého'],
    acceptedFormulas: ['CoSO4·7H2O', 'CoSO4 · 7H2O', 'CoSO₄·7H₂O', 'CoSO₄ · 7H₂O'],
  },
  {
    id: 69,
    formula: 'CaSO₄ · 2H₂O',
    name: 'síran vápenatý dihydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'CaSO₄ = síran vápenatý, 2H₂O = dihydrát. Sádrovec.',
    tip: 'di = 2. Sádrovec = CaSO₄·2H₂O. Zahříváním vzniká sádra (hemihydrát).',
    acceptedNames: ['síran vápenatý dihydrát', 'dihydrát síranu vápenatého'],
    acceptedFormulas: ['CaSO4·2H2O', 'CaSO4 · 2H2O', 'CaSO₄·2H₂O', 'CaSO₄ · 2H₂O'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PODVOJNÉ SOLI
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 70,
    formula: 'KAl(SO₄)₂',
    name: 'síran draselno-hlinitý',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Dva různé kationty K⁺ a Al³⁺, anion SO₄²⁻. Kamenec bez vody.',
    tip: 'Podvojné soli: dva různé kationty. Název aniontu + oba kationty s pomlčkou.',
    acceptedNames: ['síran draselno-hlinitý', 'síran hlinito-draselný'],
    acceptedFormulas: ['KAl(SO4)2', 'KAl(SO₄)₂'],
  },
  {
    id: 71,
    formula: 'KAl(SO₄)₂ · 12H₂O',
    name: 'síran draselno-hlinitý dodekahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Kamenec draselný. 12H₂O = dodekahydrát (dodeka = 12).',
    tip: 'dodeka = 12. Kamenec = KAl(SO₄)₂·12H₂O.',
    acceptedNames: ['síran draselno-hlinitý dodekahydrát', 'síran hlinito-draselný dodekahydrát', 'kamenec draselný'],
    acceptedFormulas: ['KAl(SO4)2·12H2O', 'KAl(SO4)2 · 12H2O', 'KAl(SO₄)₂·12H₂O', 'KAl(SO₄)₂ · 12H₂O'],
  },
  {
    id: 72,
    formula: 'NaKSO₄',
    name: 'síran sodno-draselný',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Na⁺ a K⁺ jsou dva různé kationty, SO₄²⁻ = síran.',
    tip: 'Pořadí kationtů v názvu: Na před K (abecedně) → sodno-draselný.',
    acceptedNames: ['síran sodno-draselný', 'síran draselno-sodný'],
    acceptedFormulas: ['NaKSO4', 'NaKSO₄'],
  },
  {
    id: 73,
    formula: 'CaMg(CO₃)₂',
    name: 'uhličitan vápenato-hořečnatý',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'Ca²⁺ a Mg²⁺ jsou různé kationty, CO₃²⁻ = uhličitan. Dolomit.',
    tip: 'CaMg(CO₃)₂ = dolomit. Uhličitan + vápenato-hořečnatý.',
    acceptedNames: ['uhličitan vápenato-hořečnatý', 'uhličitan hořečnato-vápenatý'],
    acceptedFormulas: ['CaMg(CO3)2', 'CaMg(CO₃)₂'],
  },
  {
    id: 74,
    formula: '(NH₄)₂Fe(SO₄)₂ · 6H₂O',
    name: 'síran amonno-železnatý hexahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'NH₄⁺ = amonný (dva), Fe²⁺ = železnatý, SO₄²⁻ = síran, 6H₂O = hexahydrát. Mohrovova sůl.',
    tip: 'Mohrowova sůl = (NH₄)₂Fe(SO₄)₂·6H₂O. Stabilní zdroj Fe²⁺.',
    acceptedNames: ['síran amonno-železnatý hexahydrát', 'síran železnato-amonný hexahydrát'],
    acceptedFormulas: ['(NH4)2Fe(SO4)2·6H2O', '(NH4)2Fe(SO4)2 · 6H2O', '(NH₄)₂Fe(SO₄)₂·6H₂O', '(NH₄)₂Fe(SO₄)₂ · 6H₂O'],
  },
  {
    id: 75,
    formula: 'NH₄Fe(SO₄)₂ · 12H₂O',
    name: 'síran amonno-železitý dodekahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'NH₄⁺ = amonný, Fe³⁺ = železitý, SO₄²⁻ = síran, 12H₂O = dodekahydrát. Železný kamenec.',
    tip: 'Železný kamenec = NH₄Fe(SO₄)₂·12H₂O. Fe³⁺ = železitý (fialový).',
    acceptedNames: ['síran amonno-železitý dodekahydrát', 'síran železito-amonný dodekahydrát'],
    acceptedFormulas: ['NH4Fe(SO4)2·12H2O', 'NH4Fe(SO4)2 · 12H2O', 'NH₄Fe(SO₄)₂·12H₂O', 'NH₄Fe(SO₄)₂ · 12H₂O'],
  },
  {
    id: 76,
    formula: 'KCr(SO₄)₂ · 12H₂O',
    name: 'síran draselno-chromitý dodekahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'K⁺ = draselný, Cr³⁺ = chromitý, SO₄²⁻ = síran, 12H₂O = dodekahydrát. Chromový kamenec.',
    tip: 'Chromový kamenec = KCr(SO₄)₂·12H₂O. Fialový, Cr = +III → chromitý.',
    acceptedNames: ['síran draselno-chromitý dodekahydrát', 'síran chromito-draselný dodekahydrát'],
    acceptedFormulas: ['KCr(SO4)2·12H2O', 'KCr(SO4)2 · 12H2O', 'KCr(SO₄)₂·12H₂O', 'KCr(SO₄)₂ · 12H₂O'],
  },
  {
    id: 77,
    formula: 'NH₄Al(SO₄)₂ · 12H₂O',
    name: 'síran amonno-hlinitý dodekahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'NH₄⁺ = amonný, Al³⁺ = hlinitý, SO₄²⁻ = síran, 12H₂O = dodekahydrát. Amonný kamenec.',
    tip: 'Amonný kamenec = NH₄Al(SO₄)₂·12H₂O. Struktura jako kamenec draselný.',
    acceptedNames: ['síran amonno-hlinitý dodekahydrát', 'síran hlinito-amonný dodekahydrát'],
    acceptedFormulas: ['NH4Al(SO4)2·12H2O', 'NH4Al(SO4)2 · 12H2O', 'NH₄Al(SO₄)₂·12H₂O', 'NH₄Al(SO₄)₂ · 12H₂O'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZÁSADITÉ SOLI
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 78,
    formula: 'Cu₂(OH)₂CO₃',
    name: 'zásaditý uhličitan měďnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Zásaditá sůl s OH⁻ skupinou. Cu²⁺ = měďnatý, CO₃²⁻ = uhličitan, OH⁻ = hydroxidová skupina. Malachit.',
    tip: 'Zásaditá sůl = sůl + OH⁻. Přidej prefix zásaditý.',
    acceptedNames: ['zásaditý uhličitan měďnatý'],
    acceptedFormulas: ['Cu2(OH)2CO3', 'Cu₂(OH)₂CO₃'],
  },
  {
    id: 79,
    formula: 'Pb(OH)Cl',
    name: 'zásaditý chlorid olovnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Pb²⁺ = olovnatý, Cl⁻ = chlorid, OH⁻ = hydroxidová skupina. Jeden Cl a jeden OH.',
    tip: 'Pb²⁺: dva anionty celkem → Cl⁻ + OH⁻.',
    acceptedNames: ['zásaditý chlorid olovnatý'],
    acceptedFormulas: ['Pb(OH)Cl', 'PbOHCl'],
  },
  {
    id: 80,
    formula: 'Al(OH)₂Cl',
    name: 'zásaditý chlorid hlinitý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý, Cl⁻ = chlorid, 2× OH⁻. Celkem tři záporné náboje.',
    tip: 'Al³⁺: tři anionty → 2× OH⁻ + 1× Cl⁻.',
    acceptedNames: ['zásaditý chlorid hlinitý'],
    acceptedFormulas: ['Al(OH)2Cl', 'Al(OH)₂Cl'],
  },
  {
    id: 81,
    formula: 'Mg(OH)Cl',
    name: 'zásaditý chlorid hořečnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, OH⁻ + Cl⁻ = celkem −2.',
    tip: 'Hořečnatý (+II): jeden OH⁻ + jeden Cl⁻.',
    acceptedNames: ['zásaditý chlorid hořečnatý'],
    acceptedFormulas: ['Mg(OH)Cl', 'MgOHCl'],
  },
  {
    id: 82,
    formula: 'Bi(OH)₂NO₃',
    name: 'zásaditý dusičnan bismutitý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Bi³⁺ = bismutitý, 2× OH⁻ + NO₃⁻ = celkem −3.',
    tip: 'Bismutitý (+III): 2× OH⁻ + 1× NO₃⁻.',
    acceptedNames: ['zásaditý dusičnan bismutitý'],
    acceptedFormulas: ['Bi(OH)2NO3', 'Bi(OH)₂NO₃'],
  },
  {
    id: 83,
    formula: 'Ca(OH)Cl',
    name: 'zásaditý chlorid vápenatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Ca²⁺ = vápenatý, OH⁻ + Cl⁻ = celkem −2. Chlorové vápno.',
    tip: 'Vápenatý (+II): jeden OH⁻ + jeden Cl⁻. Chlorové vápno = Ca(OH)Cl.',
    acceptedNames: ['zásaditý chlorid vápenatý'],
    acceptedFormulas: ['Ca(OH)Cl', 'CaOHCl'],
  },
  {
    id: 84,
    formula: 'Cu(OH)NO₃',
    name: 'zásaditý dusičnan měďnatý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Cu²⁺ = měďnatý, OH⁻ + NO₃⁻ = celkem −2.',
    tip: 'Měďnatý (+II): jeden OH⁻ + jeden NO₃⁻.',
    acceptedNames: ['zásaditý dusičnan měďnatý'],
    acceptedFormulas: ['Cu(OH)NO3', 'Cu(OH)NO₃', 'CuOHNO3', 'CuOHNO₃'],
  },
  {
    id: 85,
    formula: 'Zn(OH)Cl',
    name: 'zásaditý chlorid zinečnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Zn²⁺ = zinečnatý, OH⁻ + Cl⁻ = celkem −2.',
    tip: 'Zinečnatý (+II): jeden OH⁻ + jeden Cl⁻.',
    acceptedNames: ['zásaditý chlorid zinečnatý'],
    acceptedFormulas: ['Zn(OH)Cl', 'ZnOHCl'],
  },
  {
    id: 86,
    formula: 'Fe(OH)SO₄',
    name: 'zásaditý síran železitý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Fe³⁺ = železitý, OH⁻ + SO₄²⁻ = celkem −3. Nábojová rovnováha: −1 + (−2) = −3 = Fe³⁺.',
    tip: 'Železitý (+III): OH⁻ + SO₄²⁻ dohromady dávají −3.',
    acceptedNames: ['zásaditý síran železitý'],
    acceptedFormulas: ['Fe(OH)SO4', 'Fe(OH)SO₄', 'FeOHSO4', 'FeOHSO₄'],
  },
  {
    id: 87,
    formula: 'Pb₃(OH)₂(CO₃)₂',
    name: 'zásaditý uhličitan olovnatý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Pb²⁺ = olovnatý, 2× OH⁻ + 2× CO₃²⁻ na tři kationty. Bílé olovo — historický pigment.',
    tip: 'Bílé olovo = Pb₃(OH)₂(CO₃)₂. Zásaditá sůl s uhličitanem.',
    acceptedNames: ['zásaditý uhličitan olovnatý'],
    acceptedFormulas: ['Pb3(OH)2(CO3)2', 'Pb₃(OH)₂(CO₃)₂'],
  },
];

export const MULTIPLE_CHOICE_COUNT_MODE_A = 4;
export const MULTIPLE_CHOICE_COUNT_MODE_B = 2;
