// Databáze příkladů pro procvičování chemického názvosloví solí
// Každý příklad: formula, name, group, explanation, tip, acceptedNames[], acceptedFormulas[], difficulty (1-3)

export const GROUPS = {
  BEZKYSLICATE: 'bezkyslíkaté',
  KYSLICATE: 'kyslíkaté',
  HYDRATY: 'hydráty',
  PODVOJNE: 'podvojné',
  ZASADITE: 'zásadité',
};

export const examples = [
  // ─── SOLI BEZKYSLÍKATÝCH KYSELIN ───────────────────────────────────────────
  {
    id: 1,
    formula: 'NaCl',
    name: 'chlorid sodný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'NaCl je sůl kyseliny chlorovodíkové (HCl). Kation Na⁺ → sodný, anion Cl⁻ → chlorid. Název: chlorid sodný.',
    tip: 'U bezkyslíkatých solí: název aniontu (přípona -id) + název kationtu (přídavné jméno v 1. pádu).',
    acceptedNames: ['chlorid sodný'],
    acceptedFormulas: ['NaCl'],
  },
  {
    id: 2,
    formula: 'KBr',
    name: 'bromid draselný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'KBr je sůl kyseliny bromovodíkové (HBr). Kation K⁺ → draselný, anion Br⁻ → bromid.',
    tip: 'Br⁻ = bromid, K⁺ = draselný.',
    acceptedNames: ['bromid draselný'],
    acceptedFormulas: ['KBr'],
  },
  {
    id: 3,
    formula: 'CaF₂',
    name: 'fluorid vápenatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Ca²⁺ je vápenatý (oxidační číslo II), F⁻ → fluorid. Dva fluoridy na jeden kation vápníku: CaF₂.',
    tip: 'F⁻ = fluorid. Vápník má ox. číslo +II → vápenatý.',
    acceptedNames: ['fluorid vápenatý'],
    acceptedFormulas: ['CaF2', 'CaF₂'],
  },
  {
    id: 4,
    formula: 'FeS',
    name: 'sulfid železnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 1,
    explanation: 'Fe²⁺ = železnatý (ox. č. II), S²⁻ = sulfid. Přípona -atý/-natý označuje nižší ox. číslo přechodného kovu.',
    tip: 'FeS: železo má ox. č. +II → železnatý (nikoli železitý, to je +III).',
    acceptedNames: ['sulfid železnatý'],
    acceptedFormulas: ['FeS'],
  },
  {
    id: 5,
    formula: 'Fe₂S₃',
    name: 'sulfid železitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Fe³⁺ = železitý (ox. č. III), S²⁻ = sulfid. Dva kationty Fe³⁺ a tři anionty S²⁻ → Fe₂S₃.',
    tip: 'Fe₂S₃: dva atomy Fe, tři S → Fe musí mít ox. č. +III → železitý.',
    acceptedNames: ['sulfid železitý'],
    acceptedFormulas: ['Fe2S3', 'Fe₂S₃'],
  },
  {
    id: 6,
    formula: 'CuI',
    name: 'jodid měďný',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Cu⁺ = měďný (ox. č. I), I⁻ = jodid. CuI → jeden kation a jeden anion.',
    tip: 'Přípona -ný u přechodných kovů značí nejnižší ox. číslo: Cu⁺ = měďný, Cu²⁺ = měďnatý.',
    acceptedNames: ['jodid měďný'],
    acceptedFormulas: ['CuI'],
  },
  {
    id: 7,
    formula: 'AlCl₃',
    name: 'chlorid hlinitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý (hliník má stálé ox. č. +III), Cl⁻ = chlorid. Tři chloridy na jeden kation: AlCl₃.',
    tip: 'Hliník má vždy ox. č. +III → hlinitý.',
    acceptedNames: ['chlorid hlinitý'],
    acceptedFormulas: ['AlCl3', 'AlCl₃'],
  },
  {
    id: 8,
    formula: 'PbS₂',
    name: 'sulfid olovičitý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 3,
    explanation: 'Pb⁴⁺ = olovičitý (ox. č. IV), S²⁻ = sulfid. Jeden Pb⁴⁺ a dva S²⁻ → PbS₂.',
    tip: 'Olovo může mít ox. č. +II (olovnatý) nebo +IV (olovičitý).',
    acceptedNames: ['sulfid olovičitý'],
    acceptedFormulas: ['PbS2', 'PbS₂'],
  },
  {
    id: 9,
    formula: 'MgBr₂',
    name: 'bromid hořečnatý',
    group: GROUPS.BEZKYSLICATE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, Br⁻ = bromid. Dva bromidy na jeden kation hořčíku.',
    tip: 'Hořčík má vždy ox. č. +II → hořečnatý.',
    acceptedNames: ['bromid hořečnatý'],
    acceptedFormulas: ['MgBr2', 'MgBr₂'],
  },

  // ─── SOLI KYSLÍKATÝCH KYSELIN ──────────────────────────────────────────────
  {
    id: 10,
    formula: 'Na₂SO₄',
    name: 'síran sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Na₂SO₄ je sůl kyseliny sírové (H₂SO₄). Anion SO₄²⁻ = síran, kation Na⁺ = sodný.',
    tip: 'SO₄²⁻ = síran (kyselina sírová H₂SO₄ → sůl síran).',
    acceptedNames: ['síran sodný'],
    acceptedFormulas: ['Na2SO4', 'Na₂SO₄'],
  },
  {
    id: 11,
    formula: 'CaCO₃',
    name: 'uhličitan vápenatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'CaCO₃ je sůl kyseliny uhličité (H₂CO₃). Anion CO₃²⁻ = uhličitan, kation Ca²⁺ = vápenatý.',
    tip: 'CO₃²⁻ = uhličitan (H₂CO₃ → uhličitan). CaCO₃ je hlavní složka vápence.',
    acceptedNames: ['uhličitan vápenatý'],
    acceptedFormulas: ['CaCO3', 'CaCO₃'],
  },
  {
    id: 12,
    formula: 'KNO₃',
    name: 'dusičnan draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'KNO₃ je sůl kyseliny dusičné (HNO₃). Anion NO₃⁻ = dusičnan, kation K⁺ = draselný.',
    tip: 'NO₃⁻ = dusičnan (HNO₃ → dusičnan). KNO₃ se lidově říká ledek.',
    acceptedNames: ['dusičnan draselný'],
    acceptedFormulas: ['KNO3', 'KNO₃'],
  },
  {
    id: 13,
    formula: 'Na₃PO₄',
    name: 'fosforečnan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Na₃PO₄ je sůl kyseliny fosforečné (H₃PO₄). Anion PO₄³⁻ = fosforečnan, tři kationty Na⁺.',
    tip: 'PO₄³⁻ = fosforečnan. Tří kyselinový vodík → tři sodíky.',
    acceptedNames: ['fosforečnan sodný'],
    acceptedFormulas: ['Na3PO4', 'Na₃PO₄'],
  },
  {
    id: 14,
    formula: 'Fe₂(SO₄)₃',
    name: 'síran železitý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Fe³⁺ = železitý, SO₄²⁻ = síran. Dva kationty Fe³⁺ (celkem +6) a tři anionty SO₄²⁻ (celkem -6) → Fe₂(SO₄)₃.',
    tip: 'Závorky u SO₄ jsou nutné, pokud jich je více než jedna: (SO₄)₃.',
    acceptedNames: ['síran železitý'],
    acceptedFormulas: ['Fe2(SO4)3', 'Fe₂(SO₄)₃'],
  },
  {
    id: 15,
    formula: 'BaSO₄',
    name: 'síran barnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 1,
    explanation: 'Ba²⁺ = barnatý, SO₄²⁻ = síran. Náboje se vyruší 1:1 → BaSO₄.',
    tip: 'Baryum má vždy ox. č. +II → barnatý.',
    acceptedNames: ['síran barnatý'],
    acceptedFormulas: ['BaSO4', 'BaSO₄'],
  },
  {
    id: 16,
    formula: 'Cu(NO₃)₂',
    name: 'dusičnan měďnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Cu²⁺ = měďnatý, NO₃⁻ = dusičnan. Dva dusičnany na jeden kation mědi.',
    tip: 'Závorky: (NO₃)₂ protože je jich více. Cu²⁺ = měďnatý (Cu⁺ = měďný).',
    acceptedNames: ['dusičnan měďnatý'],
    acceptedFormulas: ['Cu(NO3)2', 'Cu(NO₃)₂'],
  },
  {
    id: 17,
    formula: 'Al₂(SO₄)₃',
    name: 'síran hlinitý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý, SO₄²⁻ = síran. Dva Al³⁺ (celkem +6) a tři SO₄²⁻ (celkem -6).',
    tip: 'Hliník je vždy +III = hlinitý. Al₂(SO₄)₃ je základní složka kamence.',
    acceptedNames: ['síran hlinitý'],
    acceptedFormulas: ['Al2(SO4)3', 'Al₂(SO₄)₃'],
  },
  {
    id: 18,
    formula: 'Mg(NO₃)₂',
    name: 'dusičnan hořečnatý',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, NO₃⁻ = dusičnan. Dva dusičnany vyrovnají náboj hořčíku.',
    tip: 'Mg je vždy +II → hořečnatý.',
    acceptedNames: ['dusičnan hořečnatý'],
    acceptedFormulas: ['Mg(NO3)2', 'Mg(NO₃)₂'],
  },
  {
    id: 19,
    formula: 'Na₂HPO₄',
    name: 'hydrogenfosforečnan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'HPO₄²⁻ = hydrogenfosforečnan (kyselina H₃PO₄ odštěpila pouze dva H⁺ ze tří). Dva sodíky.',
    tip: 'Předpona hydrogen- značí, že kyselina odštěpila o jeden proton méně, než by mohla.',
    acceptedNames: ['hydrogenfosforečnan sodný'],
    acceptedFormulas: ['Na2HPO4', 'Na₂HPO₄'],
  },
  {
    id: 20,
    formula: 'NaHCO₃',
    name: 'hydrogenuhličitan sodný',
    group: GROUPS.KYSLICATE,
    difficulty: 2,
    explanation: 'HCO₃⁻ = hydrogenuhličitan (H₂CO₃ odštěpila jen jeden H⁺). Jeden sodík.',
    tip: 'NaHCO₃ je jedlá soda. Hydrogen- = zůstal jeden kyselý vodík.',
    acceptedNames: ['hydrogenuhličitan sodný'],
    acceptedFormulas: ['NaHCO3', 'NaHCO₃'],
  },
  {
    id: 21,
    formula: 'K₂Cr₂O₇',
    name: 'dichroman draselný',
    group: GROUPS.KYSLICATE,
    difficulty: 3,
    explanation: 'Cr₂O₇²⁻ = dichroman (dva atomy chromu). K⁺ = draselný, dva kationty.',
    tip: 'Předpona di- u chromanu = dvě jednotky CrO₄. K₂Cr₂O₇ je oranžový oxidant.',
    acceptedNames: ['dichroman draselný'],
    acceptedFormulas: ['K2Cr2O7', 'K₂Cr₂O₇'],
  },

  // ─── HYDRÁTY SOLÍ ─────────────────────────────────────────────────────────
  {
    id: 22,
    formula: 'CuSO₄ · 5H₂O',
    name: 'síran měďnatý pentahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 1,
    explanation: 'Pět molekul vody krystalizační (pentahydrát). Základ: CuSO₄ = síran měďnatý.',
    tip: 'Počet molekul vody: mono=1, di=2, tri=3, tetra=4, penta=5, hexa=6, hepta=7, okta=8, nona=9, deka=10.',
    acceptedNames: ['síran měďnatý pentahydrát', 'pentahydrát síranu měďnatého'],
    acceptedFormulas: ['CuSO4·5H2O', 'CuSO4 · 5H2O', 'CuSO₄·5H₂O', 'CuSO₄ · 5H₂O'],
  },
  {
    id: 23,
    formula: 'Na₂SO₄ · 10H₂O',
    name: 'síran sodný dekahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 1,
    explanation: 'Deset molekul vody → dekahydrát. Základ: Na₂SO₄ = síran sodný. Jde o Glauberovu sůl.',
    tip: 'deka = 10. Dekahydrát = 10 molekul H₂O.',
    acceptedNames: ['síran sodný dekahydrát', 'dekahydrát síranu sodného'],
    acceptedFormulas: ['Na2SO4·10H2O', 'Na2SO4 · 10H2O', 'Na₂SO₄·10H₂O', 'Na₂SO₄ · 10H₂O'],
  },
  {
    id: 24,
    formula: 'MgSO₄ · 7H₂O',
    name: 'síran hořečnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Sedm molekul vody → heptahydrát. MgSO₄ = síran hořečnatý. Jde o Epsomskou sůl.',
    tip: 'hepta = 7. MgSO₄·7H₂O = Epsomská sůl (používaná v lékařství i kosmetice).',
    acceptedNames: ['síran hořečnatý heptahydrát', 'heptahydrát síranu hořečnatého'],
    acceptedFormulas: ['MgSO4·7H2O', 'MgSO4 · 7H2O', 'MgSO₄·7H₂O', 'MgSO₄ · 7H₂O'],
  },
  {
    id: 25,
    formula: 'CaCl₂ · 6H₂O',
    name: 'chlorid vápenatý hexahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Šest molekul vody → hexahydrát. CaCl₂ = chlorid vápenatý.',
    tip: 'hexa = 6. Bezvodý CaCl₂ se používá jako vysoušedlo.',
    acceptedNames: ['chlorid vápenatý hexahydrát', 'hexahydrát chloridu vápenatého'],
    acceptedFormulas: ['CaCl2·6H2O', 'CaCl2 · 6H2O', 'CaCl₂·6H₂O', 'CaCl₂ · 6H₂O'],
  },
  {
    id: 26,
    formula: 'FeSO₄ · 7H₂O',
    name: 'síran železnatý heptahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Fe²⁺ = železnatý, SO₄²⁻ = síran, 7H₂O = heptahydrát. Jde o zelený vitriol.',
    tip: 'Nezaměňovat se síranem železitým! FeS O₄ = železnatý (+II), Fe₂(SO₄)₃ = železitý (+III).',
    acceptedNames: ['síran železnatý heptahydrát', 'heptahydrát síranu železnatého'],
    acceptedFormulas: ['FeSO4·7H2O', 'FeSO4 · 7H2O', 'FeSO₄·7H₂O', 'FeSO₄ · 7H₂O'],
  },
  {
    id: 27,
    formula: 'Na₂CO₃ · 10H₂O',
    name: 'uhličitan sodný dekahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 2,
    explanation: 'Na₂CO₃ = uhličitan sodný, 10H₂O = dekahydrát. Jde o krystalickou sodu.',
    tip: 'Na₂CO₃ bezvodý = kalcinovaná soda, s 10H₂O = krystalická soda.',
    acceptedNames: ['uhličitan sodný dekahydrát', 'dekahydrát uhličitanu sodného'],
    acceptedFormulas: ['Na2CO3·10H2O', 'Na2CO3 · 10H2O', 'Na₂CO₃·10H₂O', 'Na₂CO₃ · 10H₂O'],
  },
  {
    id: 28,
    formula: 'AlCl₃ · 6H₂O',
    name: 'chlorid hlinitý hexahydrát',
    group: GROUPS.HYDRATY,
    difficulty: 3,
    explanation: 'Al³⁺ = hlinitý, Cl⁻ = chlorid, 6H₂O = hexahydrát.',
    tip: 'Hliník je vždy +III = hlinitý.',
    acceptedNames: ['chlorid hlinitý hexahydrát', 'hexahydrát chloridu hlinitého'],
    acceptedFormulas: ['AlCl3·6H2O', 'AlCl3 · 6H2O', 'AlCl₃·6H₂O', 'AlCl₃ · 6H₂O'],
  },

  // ─── PODVOJNÉ SOLI ─────────────────────────────────────────────────────────
  {
    id: 29,
    formula: 'KAl(SO₄)₂',
    name: 'síran draselno-hlinitý',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Podvojná sůl se dvěma různými kationty: K⁺ a Al³⁺. Anion SO₄²⁻. Název: síran + oba kationty spojené pomlčkou (v pořadí abecedním nebo dle zvyku).',
    tip: 'Podvojné soli mají dva různé kationty (nebo anionty). Název aniontu se píše jako první, pak kationty oddělené pomlčkou.',
    acceptedNames: ['síran draselno-hlinitý', 'síran hlinito-draselný'],
    acceptedFormulas: ['KAl(SO4)2', 'KAl(SO₄)₂'],
  },
  {
    id: 30,
    formula: 'KAl(SO₄)₂ · 12H₂O',
    name: 'síran draselno-hlinitý dodekahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Kamenec draselný = podvojná sůl + 12 molekul vody (dodekahydrát). dodeka = 12.',
    tip: 'dodeka = 12. Kamenec = KAl(SO₄)₂·12H₂O. Používá se v potravinářství a lékárnách.',
    acceptedNames: ['síran draselno-hlinitý dodekahydrát', 'síran hlinito-draselný dodekahydrát', 'kamenec draselný'],
    acceptedFormulas: ['KAl(SO4)2·12H2O', 'KAl(SO4)2 · 12H2O', 'KAl(SO₄)₂·12H₂O', 'KAl(SO₄)₂ · 12H₂O'],
  },
  {
    id: 31,
    formula: 'NaKSO₄',
    name: 'síran sodno-draselný',
    group: GROUPS.PODVOJNE,
    difficulty: 2,
    explanation: 'Dva různé kationty Na⁺ a K⁺, anion SO₄²⁻. Název: síran + sodno-draselný (abecedně).',
    tip: 'Pořadí kationtů v názvu: abecedně nebo dle zvyku (sodný před draselným = sodno-draselný).',
    acceptedNames: ['síran sodno-draselný', 'síran draselno-sodný'],
    acceptedFormulas: ['NaKSO4', 'NaKSO₄'],
  },
  {
    id: 32,
    formula: 'CaMg(CO₃)₂',
    name: 'uhličitan vápenato-hořečnatý',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'Ca²⁺ a Mg²⁺ jsou dva různé kationty, anion CO₃²⁻. Jde o dolomit.',
    tip: 'CaMg(CO₃)₂ = dolomit, přírodní nerost. Uhličitan + vápenato-hořečnatý.',
    acceptedNames: ['uhličitan vápenato-hořečnatý', 'uhličitan hořečnato-vápenatý'],
    acceptedFormulas: ['CaMg(CO3)2', 'CaMg(CO₃)₂'],
  },
  {
    id: 33,
    formula: 'NH₄Fe(SO₄)₂',
    name: 'síran amonno-železitý',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'NH₄⁺ = amonný, Fe³⁺ = železitý, SO₄²⁻ = síran. Mohrovský kamenec bez vody.',
    tip: 'NH₄⁺ = amonný kation. Podvojná sůl s amonným a železitým kationem.',
    acceptedNames: ['síran amonno-železitý', 'síran železito-amonný'],
    acceptedFormulas: ['NH4Fe(SO4)2', 'NH₄Fe(SO₄)₂'],
  },
  {
    id: 34,
    formula: '(NH₄)₂Fe(SO₄)₂ · 6H₂O',
    name: 'síran amonno-železnatý hexahydrát',
    group: GROUPS.PODVOJNE,
    difficulty: 3,
    explanation: 'NH₄⁺ = amonný (dva), Fe²⁺ = železnatý (jeden), SO₄²⁻ = síran (dva), 6H₂O = hexahydrát. Mohrovova sůl.',
    tip: 'Mohrovova sůl = (NH₄)₂Fe(SO₄)₂·6H₂O. Stabilní zdroj Fe²⁺ v analytické chemii.',
    acceptedNames: ['síran amonno-železnatý hexahydrát', 'síran železnato-amonný hexahydrát'],
    acceptedFormulas: ['(NH4)2Fe(SO4)2·6H2O', '(NH4)2Fe(SO4)2 · 6H2O', '(NH₄)₂Fe(SO₄)₂·6H₂O', '(NH₄)₂Fe(SO₄)₂ · 6H₂O'],
  },

  // ─── ZÁSADITÉ SOLI ─────────────────────────────────────────────────────────
  {
    id: 35,
    formula: 'Cu₂(OH)₂CO₃',
    name: 'zásaditý uhličitan měďnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Zásaditá sůl obsahuje OH⁻ skupinu. Cu²⁺ = měďnatý, CO₃²⁻ = uhličitan, OH⁻ = hydroxid. Jde o malachit.',
    tip: 'Zásaditá sůl = sůl, kde část OH⁻ nebyla nahrazena kyselinovým zbytkem. Prefix zásaditý.',
    acceptedNames: ['zásaditý uhličitan měďnatý', 'zásaditý uhličitan měďnatý (malachit)'],
    acceptedFormulas: ['Cu2(OH)2CO3', 'Cu₂(OH)₂CO₃'],
  },
  {
    id: 36,
    formula: 'Pb(OH)Cl',
    name: 'zásaditý chlorid olovnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Pb²⁺ = olovnatý, jeden anion Cl⁻ a jeden OH⁻ → zásaditá sůl. Jeden proton byl nahrazen kyselinovým zbytkem, druhý zůstal jako OH⁻.',
    tip: 'Zásaditá sůl: část bazicity (OH⁻) zůstala nereagovaná. U Pb²⁺: jeden Cl⁻ a jeden OH⁻.',
    acceptedNames: ['zásaditý chlorid olovnatý'],
    acceptedFormulas: ['Pb(OH)Cl', 'PbOHCl'],
  },
  {
    id: 37,
    formula: 'Al(OH)₂Cl',
    name: 'zásaditý chlorid hlinitý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Al³⁺ = hlinitý, dva OH⁻ a jeden Cl⁻. Dvě ze tří vazeb na bázi, jedna na kyselinový zbytek.',
    tip: 'Hlinitý (Al³⁺): celkem tři vazby → kombinace OH⁻ a Cl⁻ musí dávat celkem -3.',
    acceptedNames: ['zásaditý chlorid hlinitý'],
    acceptedFormulas: ['Al(OH)2Cl', 'Al(OH)₂Cl'],
  },
  {
    id: 38,
    formula: 'Fe(OH)SO₄',
    name: 'zásaditý síran železnatý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Fe²⁺ = železnatý, jeden OH⁻ a jeden SO₄²⁻... ale náboje nesedí (OH⁻ + SO₄²⁻ = -3 ≠ -2). Správně: Fe(OH)SO₄ = FeOHSO₄, kde Fe³⁺ = železitý... Ve skutečnosti vzorec FeOHSO₄ odpovídá Fe(III): OH⁻ + SO₄²⁻ = -3 = kation Fe³⁺ = železitý.',
    tip: 'Vždy zkontroluj nábojovou rovnováhu: součet nábojů anionů = náboj kationtu.',
    acceptedNames: ['zásaditý síran železitý'],
    acceptedFormulas: ['Fe(OH)SO4', 'Fe(OH)SO₄', 'FeOHSO4', 'FeOHSO₄'],
  },
  {
    id: 39,
    formula: 'Mg(OH)Cl',
    name: 'zásaditý chlorid hořečnatý',
    group: GROUPS.ZASADITE,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, jeden OH⁻ a jeden Cl⁻. Součet nábojů: -1 + (-1) = -2 = ox. č. Mg.',
    tip: 'Hořečnatý (Mg²⁺): dva anionty → OH⁻ + Cl⁻ (každý -1).',
    acceptedNames: ['zásaditý chlorid hořečnatý'],
    acceptedFormulas: ['Mg(OH)Cl', 'MgOHCl'],
  },
  {
    id: 40,
    formula: 'Bi(OH)₂NO₃',
    name: 'zásaditý dusičnan bismutitý',
    group: GROUPS.ZASADITE,
    difficulty: 3,
    explanation: 'Bi³⁺ = bismutitý, dva OH⁻ a jeden NO₃⁻. Nábojová rovnováha: -2 + (-1) = -3 = Bi³⁺.',
    tip: 'Bismut: ox. č. +III → bismutitý. Dva OH⁻ + jeden NO₃⁻ = -3.',
    acceptedNames: ['zásaditý dusičnan bismutitý'],
    acceptedFormulas: ['Bi(OH)2NO3', 'Bi(OH)₂NO₃'],
  },
];

// Počet prvních příkladů s multiple choice (pro každý režim)
export const MULTIPLE_CHOICE_COUNT_MODE_A = 4; // Režim A: první 4 s výběrem
export const MULTIPLE_CHOICE_COUNT_MODE_B = 2; // Režim B: první 2 s výběrem
