// Databáze příkladů pro procvičování chemického názvosloví oxidů

export const GROUPS = {
  KOVY_1_2:   'oxidy kovů I. a II. skupiny',
  KOVY_PREK:  'oxidy přechodných kovů',
  KOVY_JINE:  'oxidy ostatních kovů',
  NEKOVY:     'oxidy nekovů',
  PEROXIDY:   'peroxidy',
};

export const MULTIPLE_CHOICE_COUNT_MODE_A = 4;
export const MULTIPLE_CHOICE_COUNT_MODE_B = 2;

export const examples = [

  // ═══════════════════════════════════════════════════════════════════════════
  // OXIDY KOVŮ I. A II. SKUPINY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 1,
    formula: 'Na₂O',
    name: 'oxid sodný',
    group: GROUPS.KOVY_1_2,
    difficulty: 1,
    explanation: 'Na⁺ = sodný (ox. č. +I), dva sodíky na jeden O²⁻. Vzorec: Na₂O.',
    tip: 'Sodík = vždy +I → sodný. Dva Na⁺ na jeden O²⁻.',
    acceptedNames: ['oxid sodný'],
    acceptedFormulas: ['Na2O', 'Na₂O'],
  },
  {
    id: 2,
    formula: 'K₂O',
    name: 'oxid draselný',
    group: GROUPS.KOVY_1_2,
    difficulty: 1,
    explanation: 'K⁺ = draselný (+I), K₂O.',
    tip: 'Draslík = vždy +I → draselný.',
    acceptedNames: ['oxid draselný'],
    acceptedFormulas: ['K2O', 'K₂O'],
  },
  {
    id: 3,
    formula: 'Li₂O',
    name: 'oxid lithný',
    group: GROUPS.KOVY_1_2,
    difficulty: 2,
    explanation: 'Li⁺ = lithný (+I), Li₂O.',
    tip: 'Lithium = +I → lithný.',
    acceptedNames: ['oxid lithný'],
    acceptedFormulas: ['Li2O', 'Li₂O'],
  },
  {
    id: 4,
    formula: 'Rb₂O',
    name: 'oxid rubidný',
    group: GROUPS.KOVY_1_2,
    difficulty: 2,
    explanation: 'Rb⁺ = rubidný (+I), Rb₂O.',
    tip: 'Rubidium = +I → rubidný.',
    acceptedNames: ['oxid rubidný'],
    acceptedFormulas: ['Rb2O', 'Rb₂O'],
  },
  {
    id: 5,
    formula: 'Cs₂O',
    name: 'oxid cesný',
    group: GROUPS.KOVY_1_2,
    difficulty: 2,
    explanation: 'Cs⁺ = cesný (+I), Cs₂O.',
    tip: 'Cesium = +I → cesný.',
    acceptedNames: ['oxid cesný'],
    acceptedFormulas: ['Cs2O', 'Cs₂O'],
  },
  {
    id: 6,
    formula: 'MgO',
    name: 'oxid hořečnatý',
    group: GROUPS.KOVY_1_2,
    difficulty: 1,
    explanation: 'Mg²⁺ = hořečnatý (+II), jeden Mg na jeden O²⁻.',
    tip: 'Hořčík = vždy +II → hořečnatý. MgO = magnézie.',
    acceptedNames: ['oxid hořečnatý'],
    acceptedFormulas: ['MgO'],
  },
  {
    id: 7,
    formula: 'CaO',
    name: 'oxid vápenatý',
    group: GROUPS.KOVY_1_2,
    difficulty: 1,
    explanation: 'Ca²⁺ = vápenatý (+II), CaO.',
    tip: 'CaO = pálené vápno. Vápník = +II → vápenatý.',
    acceptedNames: ['oxid vápenatý'],
    acceptedFormulas: ['CaO'],
  },
  {
    id: 8,
    formula: 'BaO',
    name: 'oxid barnatý',
    group: GROUPS.KOVY_1_2,
    difficulty: 1,
    explanation: 'Ba²⁺ = barnatý (+II), BaO.',
    tip: 'Baryum = +II → barnatý.',
    acceptedNames: ['oxid barnatý'],
    acceptedFormulas: ['BaO'],
  },
  {
    id: 9,
    formula: 'SrO',
    name: 'oxid strontnatý',
    group: GROUPS.KOVY_1_2,
    difficulty: 2,
    explanation: 'Sr²⁺ = strontnatý (+II), SrO.',
    tip: 'Stroncium = +II → strontnatý.',
    acceptedNames: ['oxid strontnatý'],
    acceptedFormulas: ['SrO'],
  },
  {
    id: 10,
    formula: 'BeO',
    name: 'oxid berylnatý',
    group: GROUPS.KOVY_1_2,
    difficulty: 2,
    explanation: 'Be²⁺ = berylnatý (+II), BeO.',
    tip: 'Berylium = +II → berylnatý.',
    acceptedNames: ['oxid berylnatý'],
    acceptedFormulas: ['BeO'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OXIDY PŘECHODNÝCH KOVŮ
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 11,
    formula: 'FeO',
    name: 'oxid železnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 1,
    explanation: 'Fe²⁺ = železnatý (+II), FeO.',
    tip: 'FeO: poměr 1:1 → Fe má ox. č. +II → železnatý.',
    acceptedNames: ['oxid železnatý'],
    acceptedFormulas: ['FeO'],
  },
  {
    id: 12,
    formula: 'Fe₂O₃',
    name: 'oxid železitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 1,
    explanation: 'Fe³⁺ = železitý (+III), Fe₂O₃. 2×(+3) + 3×(−2) = 0.',
    tip: 'Fe₂O₃ = rez, červený okr. Tři O → ox. č. +III → železitý.',
    acceptedNames: ['oxid železitý'],
    acceptedFormulas: ['Fe2O3', 'Fe₂O₃'],
  },
  {
    id: 13,
    formula: 'Fe₃O₄',
    name: 'oxid železnato-železitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Smíšený oxid: Fe²⁺ + 2× Fe³⁺. Jiný název: magnetit (FeO·Fe₂O₃).',
    tip: 'Fe₃O₄ = magnetit. Obsahuje Fe²⁺ i Fe³⁺ → podvojný oxid.',
    acceptedNames: ['oxid železnato-železitý', 'oxid železito-železnatý'],
    acceptedFormulas: ['Fe3O4', 'Fe₃O₄'],
  },
  {
    id: 14,
    formula: 'CuO',
    name: 'oxid měďnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 1,
    explanation: 'Cu²⁺ = měďnatý (+II), CuO.',
    tip: 'CuO = černý oxid. Cu²⁺ = měďnatý.',
    acceptedNames: ['oxid měďnatý'],
    acceptedFormulas: ['CuO'],
  },
  {
    id: 15,
    formula: 'Cu₂O',
    name: 'oxid měďný',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Cu⁺ = měďný (+I), Cu₂O. Dva Cu⁺ na jeden O²⁻.',
    tip: 'Cu₂O = červený, Cu⁺ = měďný. Pozor: měďný vs měďnatý!',
    acceptedNames: ['oxid měďný'],
    acceptedFormulas: ['Cu2O', 'Cu₂O'],
  },
  {
    id: 16,
    formula: 'MnO',
    name: 'oxid manganatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Mn²⁺ = manganatý (+II), MnO.',
    tip: 'Mangan +II → manganatý. MnO je zelený.',
    acceptedNames: ['oxid manganatý'],
    acceptedFormulas: ['MnO'],
  },
  {
    id: 17,
    formula: 'MnO₂',
    name: 'oxid manganičitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Mn⁴⁺ = manganičitý (+IV), MnO₂. 1×(+4) + 2×(−2) = 0.',
    tip: 'MnO₂ = pyrolusite, černý. +IV → manganičitý (přípona -ičitý pro +IV).',
    acceptedNames: ['oxid manganičitý'],
    acceptedFormulas: ['MnO2', 'MnO₂'],
  },
  {
    id: 18,
    formula: 'Mn₂O₇',
    name: 'oxid manganistý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Mn⁷⁺ = manganistý (+VII), Mn₂O₇. 2×(+7) + 7×(−2) = 0.',
    tip: '+VII → přípona -istý (jako manganistan). Mn₂O₇ je kapalina, silný oxidant.',
    acceptedNames: ['oxid manganistý'],
    acceptedFormulas: ['Mn2O7', 'Mn₂O₇'],
  },
  {
    id: 19,
    formula: 'Mn₂O₃',
    name: 'oxid manganitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Mn³⁺ = manganitý (+III), Mn₂O₃. 2×(+3) + 3×(−2) = 0.',
    tip: '+III → přípona -itý. Mn₂O₃ je černý.',
    acceptedNames: ['oxid manganitý'],
    acceptedFormulas: ['Mn2O3', 'Mn₂O₃'],
  },
  {
    id: 20,
    formula: 'ZnO',
    name: 'oxid zinečnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 1,
    explanation: 'Zn²⁺ = zinečnatý (+II), ZnO.',
    tip: 'ZnO = zinkbílá, opalovací krémy. Zinek = +II → zinečnatý.',
    acceptedNames: ['oxid zinečnatý'],
    acceptedFormulas: ['ZnO'],
  },
  {
    id: 21,
    formula: 'NiO',
    name: 'oxid nikelnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Ni²⁺ = nikelnatý (+II), NiO.',
    tip: 'Nikl +II → nikelnatý.',
    acceptedNames: ['oxid nikelnatý'],
    acceptedFormulas: ['NiO'],
  },
  {
    id: 22,
    formula: 'Ni₂O₃',
    name: 'oxid nikeltý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Ni³⁺ = nikeltý (+III), Ni₂O₃.',
    tip: 'Nikl +III → přípona -itý → nikeltý (nikl → nikl-itý).',
    acceptedNames: ['oxid nikeltý'],
    acceptedFormulas: ['Ni2O3', 'Ni₂O₃'],
  },
  {
    id: 23,
    formula: 'CoO',
    name: 'oxid kobaltnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Co²⁺ = kobaltnatý (+II), CoO.',
    tip: 'Kobalt +II → kobaltnatý.',
    acceptedNames: ['oxid kobaltnatý'],
    acceptedFormulas: ['CoO'],
  },
  {
    id: 24,
    formula: 'Co₂O₃',
    name: 'oxid kobaltitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Co³⁺ = kobaltitý (+III), Co₂O₃.',
    tip: '+III → přípona -itý → kobaltitý.',
    acceptedNames: ['oxid kobaltitý'],
    acceptedFormulas: ['Co2O3', 'Co₂O₃'],
  },
  {
    id: 25,
    formula: 'CrO',
    name: 'oxid chromatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Cr²⁺ = chromatý (+II), CrO.',
    tip: 'Chrom +II → chromatý (méně časté ox. č. chromu).',
    acceptedNames: ['oxid chromatý'],
    acceptedFormulas: ['CrO'],
  },
  {
    id: 26,
    formula: 'Cr₂O₃',
    name: 'oxid chromitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Cr³⁺ = chromitý (+III), Cr₂O₃. 2×(+3) + 3×(−2) = 0.',
    tip: 'Cr₂O₃ = zelená chromová barva. +III → chromitý.',
    acceptedNames: ['oxid chromitý'],
    acceptedFormulas: ['Cr2O3', 'Cr₂O₃'],
  },
  {
    id: 27,
    formula: 'CrO₃',
    name: 'oxid chromový',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Cr⁶⁺ = chromový (+VI), CrO₃. 1×(+6) + 3×(−2) = 0.',
    tip: 'CrO₃ = červený, silný oxidant. +VI → přípona -ový → chromový.',
    acceptedNames: ['oxid chromový'],
    acceptedFormulas: ['CrO3', 'CrO₃'],
  },
  {
    id: 28,
    formula: 'TiO₂',
    name: 'oxid titaničitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Ti⁴⁺ = titaničitý (+IV), TiO₂. 1×(+4) + 2×(−2) = 0.',
    tip: 'TiO₂ = titanová běloba, bílý pigment. +IV → přípona -ičitý.',
    acceptedNames: ['oxid titaničitý'],
    acceptedFormulas: ['TiO2', 'TiO₂'],
  },
  {
    id: 29,
    formula: 'Ti₂O₃',
    name: 'oxid titanitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Ti³⁺ = titanitý (+III), Ti₂O₃.',
    tip: '+III → přípona -itý → titanitý.',
    acceptedNames: ['oxid titanitý'],
    acceptedFormulas: ['Ti2O3', 'Ti₂O₃'],
  },
  {
    id: 30,
    formula: 'V₂O₅',
    name: 'oxid vanadičný',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'V⁵⁺ = vanadičný (+V), V₂O₅. 2×(+5) + 5×(−2) = 0.',
    tip: 'V₂O₅ = katalyzátor výroby H₂SO₄. +V → přípona -ičný → vanadičný.',
    acceptedNames: ['oxid vanadičný'],
    acceptedFormulas: ['V2O5', 'V₂O₅'],
  },
  {
    id: 31,
    formula: 'V₂O₃',
    name: 'oxid vanadičitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'V³⁺ = vanadičitý (+III), V₂O₃.',
    tip: '+III → přípona -ičitý (analogie s chromitý, manganitý).',
    acceptedNames: ['oxid vanadičitý'],
    acceptedFormulas: ['V2O3', 'V₂O₃'],
  },
  {
    id: 32,
    formula: 'VO',
    name: 'oxid vanadnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'V²⁺ = vanadnatý (+II), VO.',
    tip: '+II → přípona -natý → vanadnatý.',
    acceptedNames: ['oxid vanadnatý'],
    acceptedFormulas: ['VO'],
  },
  {
    id: 33,
    formula: 'WO₃',
    name: 'oxid wolframový',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'W⁶⁺ = wolframový (+VI), WO₃. 1×(+6) + 3×(−2) = 0.',
    tip: '+VI → přípona -ový → wolframový.',
    acceptedNames: ['oxid wolframový'],
    acceptedFormulas: ['WO3', 'WO₃'],
  },
  {
    id: 34,
    formula: 'MoO₃',
    name: 'oxid molybdenový',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Mo⁶⁺ = molybdenový (+VI), MoO₃.',
    tip: '+VI → přípona -ový → molybdenový.',
    acceptedNames: ['oxid molybdenový'],
    acceptedFormulas: ['MoO3', 'MoO₃'],
  },
  {
    id: 35,
    formula: 'AgO',
    name: 'oxid stříbrný',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Ag²⁺ = stříbrný v tomto případě (+II), AgO.',
    tip: 'Ag obvykle +I (měďný typ), ale AgO má Ag v ox. č. +II.',
    acceptedNames: ['oxid stříbrný'],
    acceptedFormulas: ['AgO'],
  },
  {
    id: 36,
    formula: 'Ag₂O',
    name: 'oxid stříbrný',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Ag⁺ = stříbrný (+I), Ag₂O. Oba vzorce AgO i Ag₂O mají přiřazen stejný název.',
    tip: 'Ag₂O: dva Ag⁺ na jeden O²⁻, ox. č. Ag = +I → stříbrný.',
    acceptedNames: ['oxid stříbrný'],
    acceptedFormulas: ['Ag2O', 'Ag₂O'],
  },
  {
    id: 37,
    formula: 'HgO',
    name: 'oxid rtuťnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 2,
    explanation: 'Hg²⁺ = rtuťnatý (+II), HgO.',
    tip: 'Hg²⁺ = rtuťnatý. HgO je červený nebo žlutý.',
    acceptedNames: ['oxid rtuťnatý'],
    acceptedFormulas: ['HgO'],
  },
  {
    id: 38,
    formula: 'Hg₂O',
    name: 'oxid rtuťný',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Hg₂²⁺ (rtuťný kation, dva Hg+I), Hg₂O.',
    tip: 'Hg⁺ = rtuťný (kation Hg₂²⁺). Pozor na rtuťný vs rtuťnatý!',
    acceptedNames: ['oxid rtuťný'],
    acceptedFormulas: ['Hg2O', 'Hg₂O'],
  },
  {
    id: 39,
    formula: 'PdO',
    name: 'oxid palladnatý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Pd²⁺ = palladnatý (+II), PdO.',
    tip: 'Palladium +II → palladnatý.',
    acceptedNames: ['oxid palladnatý'],
    acceptedFormulas: ['PdO'],
  },
  {
    id: 40,
    formula: 'PtO₂',
    name: 'oxid platničitý',
    group: GROUPS.KOVY_PREK,
    difficulty: 3,
    explanation: 'Pt⁴⁺ = platničitý (+IV), PtO₂.',
    tip: 'Platina +IV → platničitý (přípona -ičitý).',
    acceptedNames: ['oxid platničitý'],
    acceptedFormulas: ['PtO2', 'PtO₂'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OXIDY OSTATNÍCH KOVŮ (p-blok + vzácné zeminy)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 41,
    formula: 'Al₂O₃',
    name: 'oxid hlinitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 1,
    explanation: 'Al³⁺ = hlinitý (+III), Al₂O₃. 2×(+3) + 3×(−2) = 0.',
    tip: 'Al₂O₃ = korund, rubín, safír. Hliník = +III → hlinitý.',
    acceptedNames: ['oxid hlinitý'],
    acceptedFormulas: ['Al2O3', 'Al₂O₃'],
  },
  {
    id: 42,
    formula: 'SnO',
    name: 'oxid cínatý',
    group: GROUPS.KOVY_JINE,
    difficulty: 2,
    explanation: 'Sn²⁺ = cínatý (+II), SnO.',
    tip: 'Cín +II → cínatý (nižší ox. č.).',
    acceptedNames: ['oxid cínatý'],
    acceptedFormulas: ['SnO'],
  },
  {
    id: 43,
    formula: 'SnO₂',
    name: 'oxid cíničitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 2,
    explanation: 'Sn⁴⁺ = cíničitý (+IV), SnO₂.',
    tip: 'SnO₂ = kasiterit, ruda cínu. +IV → přípona -ičitý.',
    acceptedNames: ['oxid cíničitý'],
    acceptedFormulas: ['SnO2', 'SnO₂'],
  },
  {
    id: 44,
    formula: 'PbO',
    name: 'oxid olovnatý',
    group: GROUPS.KOVY_JINE,
    difficulty: 1,
    explanation: 'Pb²⁺ = olovnatý (+II), PbO.',
    tip: 'PbO = lythargit (žlutý). Pb +II → olovnatý.',
    acceptedNames: ['oxid olovnatý'],
    acceptedFormulas: ['PbO'],
  },
  {
    id: 45,
    formula: 'PbO₂',
    name: 'oxid olovičitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 2,
    explanation: 'Pb⁴⁺ = olovičitý (+IV), PbO₂. 1×(+4) + 2×(−2) = 0.',
    tip: 'PbO₂ = hnědočerný oxidant. +IV → olovičitý.',
    acceptedNames: ['oxid olovičitý'],
    acceptedFormulas: ['PbO2', 'PbO₂'],
  },
  {
    id: 46,
    formula: 'Pb₃O₄',
    name: 'oxid olovnato-olovičitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Smíšený oxid Pb²⁺ a Pb⁴⁺ (2PbO·PbO₂). Miniová červeň.',
    tip: 'Pb₃O₄ = minium (červená barva). Podvojný oxid Pb²⁺ + Pb⁴⁺.',
    acceptedNames: ['oxid olovnato-olovičitý', 'oxid olovičito-olovnatý'],
    acceptedFormulas: ['Pb3O4', 'Pb₃O₄'],
  },
  {
    id: 47,
    formula: 'In₂O₃',
    name: 'oxid inditý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'In³⁺ = inditý (+III), In₂O₃.',
    tip: 'Indium = +III → inditý.',
    acceptedNames: ['oxid inditý'],
    acceptedFormulas: ['In2O3', 'In₂O₃'],
  },
  {
    id: 48,
    formula: 'Tl₂O',
    name: 'oxid thallný',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Tl⁺ = thallný (+I), Tl₂O.',
    tip: 'Thalium +I → thallný.',
    acceptedNames: ['oxid thallný'],
    acceptedFormulas: ['Tl2O', 'Tl₂O'],
  },
  {
    id: 49,
    formula: 'Tl₂O₃',
    name: 'oxid thallitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Tl³⁺ = thallitý (+III), Tl₂O₃.',
    tip: 'Thalium +III → thallitý.',
    acceptedNames: ['oxid thallitý'],
    acceptedFormulas: ['Tl2O3', 'Tl₂O₃'],
  },
  {
    id: 50,
    formula: 'Bi₂O₃',
    name: 'oxid bismutitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 2,
    explanation: 'Bi³⁺ = bismutitý (+III), Bi₂O₃.',
    tip: 'Bismut = +III → bismutitý.',
    acceptedNames: ['oxid bismutitý'],
    acceptedFormulas: ['Bi2O3', 'Bi₂O₃'],
  },
  {
    id: 51,
    formula: 'Bi₂O₅',
    name: 'oxid bismutičný',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Bi⁵⁺ = bismutičný (+V), Bi₂O₅.',
    tip: '+V → přípona -ičný → bismutičný.',
    acceptedNames: ['oxid bismutičný'],
    acceptedFormulas: ['Bi2O5', 'Bi₂O₅'],
  },
  {
    id: 52,
    formula: 'Ga₂O₃',
    name: 'oxid gallitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Ga³⁺ = gallitý (+III), Ga₂O₃.',
    tip: 'Gallium +III → gallitý.',
    acceptedNames: ['oxid gallitý'],
    acceptedFormulas: ['Ga2O3', 'Ga₂O₃'],
  },
  {
    id: 53,
    formula: 'La₂O₃',
    name: 'oxid lanthanitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'La³⁺ = lanthanitý (+III), La₂O₃.',
    tip: 'Lanthan = +III → lanthanitý.',
    acceptedNames: ['oxid lanthanitý'],
    acceptedFormulas: ['La2O3', 'La₂O₃'],
  },
  {
    id: 54,
    formula: 'Ce₂O₃',
    name: 'oxid ceritý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Ce³⁺ = ceritý (+III), Ce₂O₃.',
    tip: 'Cerium +III → ceritý.',
    acceptedNames: ['oxid ceritý'],
    acceptedFormulas: ['Ce2O3', 'Ce₂O₃'],
  },
  {
    id: 55,
    formula: 'CeO₂',
    name: 'oxid ceričitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 3,
    explanation: 'Ce⁴⁺ = ceričitý (+IV), CeO₂.',
    tip: 'Cerium +IV → ceričitý. CeO₂ = katalyzátor v katalyzátorech aut.',
    acceptedNames: ['oxid ceričitý'],
    acceptedFormulas: ['CeO2', 'CeO₂'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OXIDY NEKOVŮ
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 56,
    formula: 'CO',
    name: 'oxid uhelnatý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'C má ox. č. +II (jeden kyslík). U nekovů: ox. č. +II → přípona -natý.',
    tip: 'CO = jedovatý plyn (oxid uhelnatý). Ox. č. C = +II → uhelnatý.',
    acceptedNames: ['oxid uhelnatý'],
    acceptedFormulas: ['CO'],
  },
  {
    id: 57,
    formula: 'CO₂',
    name: 'oxid uhličitý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'C má ox. č. +IV (dva kyslíky). +IV → přípona -ičitý.',
    tip: 'CO₂ = skleníkový plyn. Ox. č. C = +IV → uhličitý.',
    acceptedNames: ['oxid uhličitý'],
    acceptedFormulas: ['CO2', 'CO₂'],
  },
  {
    id: 58,
    formula: 'SO₂',
    name: 'oxid siřičitý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'S má ox. č. +IV, SO₂. +IV → přípona -ičitý.',
    tip: 'SO₂ = kyselý déšť, konzervant E220. Ox. č. S = +IV → siřičitý.',
    acceptedNames: ['oxid siřičitý'],
    acceptedFormulas: ['SO2', 'SO₂'],
  },
  {
    id: 59,
    formula: 'SO₃',
    name: 'oxid sírový',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'S má ox. č. +VI, SO₃. +VI → přípona -ový.',
    tip: 'SO₃ + H₂O → H₂SO₄. Ox. č. S = +VI → sírový.',
    acceptedNames: ['oxid sírový'],
    acceptedFormulas: ['SO3', 'SO₃'],
  },
  {
    id: 60,
    formula: 'NO',
    name: 'oxid dusnatý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'N má ox. č. +II, NO. +II → přípona -natý.',
    tip: 'NO = signální molekula v těle (vasodilatace). +II → dusnatý.',
    acceptedNames: ['oxid dusnatý'],
    acceptedFormulas: ['NO'],
  },
  {
    id: 61,
    formula: 'NO₂',
    name: 'oxid dusičitý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'N má ox. č. +IV, NO₂. +IV → přípona -ičitý.',
    tip: 'NO₂ = hnědočervený jedovatý plyn. +IV → dusičitý.',
    acceptedNames: ['oxid dusičitý'],
    acceptedFormulas: ['NO2', 'NO₂'],
  },
  {
    id: 62,
    formula: 'N₂O',
    name: 'oxid dusný',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'N má ox. č. +I, N₂O. +I → přípona -ný.',
    tip: 'N₂O = rajský plyn, anestetikum. Ox. č. N = +I → dusný.',
    acceptedNames: ['oxid dusný'],
    acceptedFormulas: ['N2O', 'N₂O'],
  },
  {
    id: 63,
    formula: 'N₂O₃',
    name: 'oxid dusitý',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'N má ox. č. +III, N₂O₃. +III → přípona -itý.',
    tip: 'N₂O₃ anhydrid kyseliny dusité. +III → dusitý.',
    acceptedNames: ['oxid dusitý'],
    acceptedFormulas: ['N2O3', 'N₂O₃'],
  },
  {
    id: 64,
    formula: 'N₂O₅',
    name: 'oxid dusičný',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'N má ox. č. +V, N₂O₅. +V → přípona -ičný.',
    tip: 'N₂O₅ anhydrid kyseliny dusičné. +V → dusičný.',
    acceptedNames: ['oxid dusičný'],
    acceptedFormulas: ['N2O5', 'N₂O₅'],
  },
  {
    id: 65,
    formula: 'P₂O₃',
    name: 'oxid fosforný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'P má ox. č. +III, P₂O₃. +III → přípona -itý, ale u P se tradičně říká fosforný (+III).',
    tip: 'Pozor: P +III → fosforný (výjimka v tradičním názvosloví).',
    acceptedNames: ['oxid fosforný'],
    acceptedFormulas: ['P2O3', 'P₂O₃'],
  },
  {
    id: 66,
    formula: 'P₂O₅',
    name: 'oxid fosforečný',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'P má ox. č. +V, P₂O₅. +V → přípona -ičný → fosforečný.',
    tip: 'P₂O₅ = silné vysoušedlo. +V → fosforečný (anhydrid H₃PO₄).',
    acceptedNames: ['oxid fosforečný'],
    acceptedFormulas: ['P2O5', 'P₂O₅'],
  },
  {
    id: 67,
    formula: 'As₂O₃',
    name: 'oxid arsenitý',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'As má ox. č. +III, As₂O₃. +III → přípona -itý.',
    tip: 'As₂O₃ = arsenový jed (nejznámější smrtelný jed). +III → arsenitý.',
    acceptedNames: ['oxid arsenitý'],
    acceptedFormulas: ['As2O3', 'As₂O₃'],
  },
  {
    id: 68,
    formula: 'As₂O₅',
    name: 'oxid arseničný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'As má ox. č. +V, As₂O₅. +V → přípona -ičný.',
    tip: '+V → arseničný (anhydrid kyseliny arseničné).',
    acceptedNames: ['oxid arseničný'],
    acceptedFormulas: ['As2O5', 'As₂O₅'],
  },
  {
    id: 69,
    formula: 'Cl₂O',
    name: 'oxid chlorný',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'Cl má ox. č. +I, Cl₂O. +I → přípona -ný.',
    tip: 'Cl₂O = anhydrid kyseliny chlorné (bělení). +I → chlorný.',
    acceptedNames: ['oxid chlorný'],
    acceptedFormulas: ['Cl2O', 'Cl₂O'],
  },
  {
    id: 70,
    formula: 'ClO₂',
    name: 'oxid chloričitý',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'Cl má ox. č. +IV, ClO₂. +IV → přípona -ičitý.',
    tip: 'ClO₂ = desinfekce vody. +IV → chloričitý.',
    acceptedNames: ['oxid chloričitý'],
    acceptedFormulas: ['ClO2', 'ClO₂'],
  },
  {
    id: 71,
    formula: 'Cl₂O₅',
    name: 'oxid chloričný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Cl má ox. č. +V, Cl₂O₅. +V → přípona -ičný.',
    tip: '+V → chloričný (anhydrid kyseliny chloričné).',
    acceptedNames: ['oxid chloričný'],
    acceptedFormulas: ['Cl2O5', 'Cl₂O₅'],
  },
  {
    id: 72,
    formula: 'Cl₂O₇',
    name: 'oxid chloristý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Cl má ox. č. +VII, Cl₂O₇. +VII → přípona -istý.',
    tip: 'Cl₂O₇ = anhydrid kyseliny chloristé. +VII → chloristý.',
    acceptedNames: ['oxid chloristý'],
    acceptedFormulas: ['Cl2O7', 'Cl₂O₇'],
  },
  {
    id: 73,
    formula: 'Cl₂O₃',
    name: 'oxid chloritý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Cl má ox. č. +III, Cl₂O₃. +III → přípona -itý.',
    tip: '+III → chloritý (anhydrid kyseliny chlorité).',
    acceptedNames: ['oxid chloritý'],
    acceptedFormulas: ['Cl2O3', 'Cl₂O₃'],
  },
  {
    id: 74,
    formula: 'I₂O₅',
    name: 'oxid jodičný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'I má ox. č. +V, I₂O₅. +V → přípona -ičný.',
    tip: 'I₂O₅ = analytické činidlo na CO. +V → jodičný.',
    acceptedNames: ['oxid jodičný'],
    acceptedFormulas: ['I2O5', 'I₂O₅'],
  },
  {
    id: 75,
    formula: 'Br₂O',
    name: 'oxid bromný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Br má ox. č. +I, Br₂O. +I → přípona -ný.',
    tip: '+I → bromný.',
    acceptedNames: ['oxid bromný'],
    acceptedFormulas: ['Br2O', 'Br₂O'],
  },
  {
    id: 76,
    formula: 'SiO₂',
    name: 'oxid křemičitý',
    group: GROUPS.NEKOVY,
    difficulty: 1,
    explanation: 'Si má ox. č. +IV, SiO₂. +IV → přípona -ičitý.',
    tip: 'SiO₂ = křemen, písek, sklo. +IV → křemičitý.',
    acceptedNames: ['oxid křemičitý'],
    acceptedFormulas: ['SiO2', 'SiO₂'],
  },
  {
    id: 77,
    formula: 'B₂O₃',
    name: 'oxid boritý',
    group: GROUPS.NEKOVY,
    difficulty: 2,
    explanation: 'B má ox. č. +III, B₂O₃. +III → přípona -itý.',
    tip: 'B₂O₃ = anhydrid kyseliny borité. +III → boritý.',
    acceptedNames: ['oxid boritý'],
    acceptedFormulas: ['B2O3', 'B₂O₃'],
  },
  {
    id: 78,
    formula: 'SeO₂',
    name: 'oxid seleničitý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Se má ox. č. +IV, SeO₂. +IV → přípona -ičitý.',
    tip: '+IV → seleničitý (analogie SO₂ = siřičitý).',
    acceptedNames: ['oxid seleničitý'],
    acceptedFormulas: ['SeO2', 'SeO₂'],
  },
  {
    id: 79,
    formula: 'SeO₃',
    name: 'oxid selenový',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Se má ox. č. +VI, SeO₃. +VI → přípona -ový.',
    tip: '+VI → selenový (analogie SO₃ = sírový).',
    acceptedNames: ['oxid selenový'],
    acceptedFormulas: ['SeO3', 'SeO₃'],
  },
  {
    id: 80,
    formula: 'TeO₂',
    name: 'oxid telluričitý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Te má ox. č. +IV, TeO₂. +IV → přípona -ičitý.',
    tip: '+IV → telluričitý.',
    acceptedNames: ['oxid telluričitý'],
    acceptedFormulas: ['TeO2', 'TeO₂'],
  },
  {
    id: 81,
    formula: 'TeO₃',
    name: 'oxid tellurový',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Te má ox. č. +VI, TeO₃. +VI → přípona -ový.',
    tip: '+VI → tellurový.',
    acceptedNames: ['oxid tellurový'],
    acceptedFormulas: ['TeO3', 'TeO₃'],
  },
  {
    id: 82,
    formula: 'OF₂',
    name: 'fluorid kyslíku',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'F je elektronegativnější než O → O dostane kladné ox. číslo. Jde o fluorid, ne oxid.',
    tip: 'OF₂ se nenazývá oxid, protože F má vyšší elektronegativitu než O.',
    acceptedNames: ['fluorid kyslíku'],
    acceptedFormulas: ['OF2', 'OF₂'],
  },
  {
    id: 83,
    formula: 'N₂O₄',
    name: 'oxid dusičitý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'N₂O₄ je dimer NO₂, ox. č. N = +IV. Stejný název jako NO₂.',
    tip: 'N₂O₄ ⇌ 2 NO₂ (rovnováha). Oba mají N v +IV → oxid dusičitý.',
    acceptedNames: ['oxid dusičitý'],
    acceptedFormulas: ['N2O4', 'N₂O₄'],
  },
  {
    id: 84,
    formula: 'Xe₂O',
    name: 'oxid xenonný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Xe má ox. č. +I (vzácné). Xenon tvoří oxidy výjimečně.',
    tip: 'Xenon +I → xenonný. Xenonové oxidy jsou vzácné a nestabilní.',
    acceptedNames: ['oxid xenonný'],
    acceptedFormulas: ['Xe2O', 'Xe₂O'],
  },
  {
    id: 85,
    formula: 'XeO₃',
    name: 'oxid xenoničitý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Xe má ox. č. +VI v XeO₃. +VI → přípona -ový, ale standardně se říká xenoničitý.',
    tip: 'XeO₃ je výbušný bílý pevný materiál. Xenon +VI.',
    acceptedNames: ['oxid xenoničitý', 'oxid xenonový'],
    acceptedFormulas: ['XeO3', 'XeO₃'],
  },
  {
    id: 86,
    formula: 'XeO₄',
    name: 'oxid xenonový',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Xe má ox. č. +VIII v XeO₄. +VIII → přípona -ový.',
    tip: 'XeO₄ je extrémně nestabilní. Xenon +VIII → xenonový.',
    acceptedNames: ['oxid xenonový'],
    acceptedFormulas: ['XeO4', 'XeO₄'],
  },
  {
    id: 87,
    formula: 'Sb₂O₃',
    name: 'oxid antimonitý',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Sb má ox. č. +III, Sb₂O₃. +III → přípona -itý.',
    tip: 'Antimon +III → antimonitý.',
    acceptedNames: ['oxid antimonitý'],
    acceptedFormulas: ['Sb2O3', 'Sb₂O₃'],
  },
  {
    id: 88,
    formula: 'Sb₂O₅',
    name: 'oxid antimoničný',
    group: GROUPS.NEKOVY,
    difficulty: 3,
    explanation: 'Sb má ox. č. +V, Sb₂O₅. +V → přípona -ičný.',
    tip: 'Antimon +V → antimoničný.',
    acceptedNames: ['oxid antimoničný'],
    acceptedFormulas: ['Sb2O5', 'Sb₂O₅'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PEROXIDY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 89,
    formula: 'H₂O₂',
    name: 'peroxid vodíku',
    group: GROUPS.PEROXIDY,
    difficulty: 1,
    explanation: 'H₂O₂ = peroxid (skupina O₂²⁻). H má ox. č. +I, O má −I (ne −II).',
    tip: 'H₂O₂ = peroxid vodíku (3% roztok = antiseptikum). Ox. č. O = −I!',
    acceptedNames: ['peroxid vodíku'],
    acceptedFormulas: ['H2O2', 'H₂O₂'],
  },
  {
    id: 90,
    formula: 'Na₂O₂',
    name: 'peroxid sodný',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'Na⁺ = sodný, O₂²⁻ = peroxidový anion. Dva sodíky.',
    tip: 'Na₂O₂ reaguje s vodou za vzniku H₂O₂ a NaOH.',
    acceptedNames: ['peroxid sodný'],
    acceptedFormulas: ['Na2O2', 'Na₂O₂'],
  },
  {
    id: 91,
    formula: 'K₂O₂',
    name: 'peroxid draselný',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'K⁺ = draselný, O₂²⁻ = peroxidový anion.',
    tip: 'Analogie s Na₂O₂ — peroxid draselný.',
    acceptedNames: ['peroxid draselný'],
    acceptedFormulas: ['K2O2', 'K₂O₂'],
  },
  {
    id: 92,
    formula: 'BaO₂',
    name: 'peroxid barnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'Ba²⁺ = barnatý, O₂²⁻ = peroxidový anion. Poměr 1:1.',
    tip: 'BaO₂ = průmyslový zdroj H₂O₂.',
    acceptedNames: ['peroxid barnatý'],
    acceptedFormulas: ['BaO2', 'BaO₂'],
  },
  {
    id: 93,
    formula: 'CaO₂',
    name: 'peroxid vápenatý',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'Ca²⁺ = vápenatý, O₂²⁻ = peroxidový anion.',
    tip: 'CaO₂ se používá v zemědělství k provzdušňování půdy.',
    acceptedNames: ['peroxid vápenatý'],
    acceptedFormulas: ['CaO2', 'CaO₂'],
  },
  {
    id: 94,
    formula: 'MgO₂',
    name: 'peroxid hořečnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'Mg²⁺ = hořečnatý, O₂²⁻ = peroxidový anion.',
    tip: 'MgO₂ = peroxid hořečnatý. Analogie s CaO₂.',
    acceptedNames: ['peroxid hořečnatý'],
    acceptedFormulas: ['MgO2', 'MgO₂'],
  },
  {
    id: 95,
    formula: 'SrO₂',
    name: 'peroxid strontnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Sr²⁺ = strontnatý, O₂²⁻ = peroxidový anion.',
    tip: 'SrO₂ = peroxid strontnatý. Analogie s BaO₂.',
    acceptedNames: ['peroxid strontnatý'],
    acceptedFormulas: ['SrO2', 'SrO₂'],
  },
  {
    id: 96,
    formula: 'ZnO₂',
    name: 'peroxid zinečnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Zn²⁺ = zinečnatý, O₂²⁻ = peroxidový anion.',
    tip: 'ZnO₂ je nestabilní peroxid. Zinek = +II → zinečnatý.',
    acceptedNames: ['peroxid zinečnatý'],
    acceptedFormulas: ['ZnO2', 'ZnO₂'],
  },
  {
    id: 97,
    formula: 'Li₂O₂',
    name: 'peroxid lithný',
    group: GROUPS.PEROXIDY,
    difficulty: 2,
    explanation: 'Li⁺ = lithný (+I), O₂²⁻ = peroxidový anion. Dva lithia.',
    tip: 'Li₂O₂ = peroxid lithný. Analogie s Na₂O₂.',
    acceptedNames: ['peroxid lithný'],
    acceptedFormulas: ['Li2O2', 'Li₂O₂'],
  },
  {
    id: 98,
    formula: 'Rb₂O₂',
    name: 'peroxid rubidný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Rb⁺ = rubidný (+I), O₂²⁻ = peroxidový anion.',
    tip: 'Rb₂O₂ = peroxid rubidný. Analogie s K₂O₂.',
    acceptedNames: ['peroxid rubidný'],
    acceptedFormulas: ['Rb2O2', 'Rb₂O₂'],
  },
  {
    id: 99,
    formula: 'Cs₂O₂',
    name: 'peroxid cesný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Cs⁺ = cesný (+I), O₂²⁻ = peroxidový anion.',
    tip: 'Cs₂O₂ = peroxid cesný. Analogie s Rb₂O₂.',
    acceptedNames: ['peroxid cesný'],
    acceptedFormulas: ['Cs2O2', 'Cs₂O₂'],
  },
  {
    id: 100,
    formula: 'FeO₂',
    name: 'peroxid železnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Fe²⁺ = železnatý, O₂²⁻ = peroxidový anion. FeO₂ (interpretace jako peroxid).',
    tip: 'Rozlišuj: FeO (oxid železnatý) vs FeO₂ (peroxid železnatý).',
    acceptedNames: ['peroxid železnatý'],
    acceptedFormulas: ['FeO2', 'FeO₂'],
  },
  {
    id: 101,
    formula: 'Cu₂O₂',
    name: 'peroxid měďný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Cu⁺ = měďný (+I), O₂²⁻ = peroxidový anion.',
    tip: 'Cu₂O₂ = peroxid měďný. Analogie s Na₂O₂.',
    acceptedNames: ['peroxid měďný'],
    acceptedFormulas: ['Cu2O2', 'Cu₂O₂'],
  },
  {
    id: 102,
    formula: 'CuO₂',
    name: 'peroxid měďnatý',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Cu²⁺ = měďnatý (+II), O₂²⁻ = peroxidový anion.',
    tip: 'CuO₂ = peroxid měďnatý. Ox. č. Cu = +II.',
    acceptedNames: ['peroxid měďnatý'],
    acceptedFormulas: ['CuO2', 'CuO₂'],
  },
  {
    id: 103,
    formula: 'PbO₂',
    name: 'oxid olovičitý',
    group: GROUPS.KOVY_JINE,
    difficulty: 2,
    explanation: 'Pb⁴⁺ = olovičitý (+IV), PbO₂ — jde o normální oxid, ne peroxid.',
    tip: 'PbO₂ ≠ peroxid! O má ox. č. −II normálně, Pb = +IV → olovičitý.',
    acceptedNames: ['oxid olovičitý'],
    acceptedFormulas: ['PbO2', 'PbO₂'],
  },

  // Bonus: superoxidy a ozonidy
  {
    id: 104,
    formula: 'KO₂',
    name: 'superoxid draselný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Obsahuje superoxidový anion O₂⁻ (ox. č. O = −½). K⁺ = draselný.',
    tip: 'KO₂ = superoxid (O₂⁻, ne O₂²⁻). Vzniká hořením K v přebytku O₂.',
    acceptedNames: ['superoxid draselný'],
    acceptedFormulas: ['KO2', 'KO₂'],
  },
  {
    id: 105,
    formula: 'NaO₂',
    name: 'superoxid sodný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Obsahuje superoxidový anion O₂⁻. Na⁺ = sodný.',
    tip: 'NaO₂ = superoxid sodný. Méně stabilní než KO₂.',
    acceptedNames: ['superoxid sodný'],
    acceptedFormulas: ['NaO2', 'NaO₂'],
  },
  {
    id: 106,
    formula: 'RbO₂',
    name: 'superoxid rubidný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Obsahuje superoxidový anion O₂⁻. Rb⁺ = rubidný.',
    tip: 'Rubidium hoří v O₂ → superoxid RbO₂.',
    acceptedNames: ['superoxid rubidný'],
    acceptedFormulas: ['RbO2', 'RbO₂'],
  },
  {
    id: 107,
    formula: 'CsO₂',
    name: 'superoxid cesný',
    group: GROUPS.PEROXIDY,
    difficulty: 3,
    explanation: 'Obsahuje superoxidový anion O₂⁻. Cs⁺ = cesný.',
    tip: 'Cesium hoří v O₂ → superoxid CsO₂.',
    acceptedNames: ['superoxid cesný'],
    acceptedFormulas: ['CsO2', 'CsO₂'],
  },
];
